### ISSUE TITLE
Integrate an OAuth provider (server-side)

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#10]
Casdoor acts like both a OAuth client and OAuth server:

1. For the Casdoor user applications (e.g., a forum or a blog system that uses Casdoor to manager login and permissions), Casdoor will behave as the OAuth service providers.
2. For real 3rd-party identity providers like Gmail, Google, WeChat, Casdoor will act as an OAuth client.

We need to choose which lib in Golang for both OAuth client and server-side.

**Comment by RobotHuang** [comment]
[golang/oauth2](https://github.com/golang/oauth2) could serve as both OAuth server-side and OAuth client, but it seems not support  WeChat and other Chinese applications.
(go-oauth2/oauth2)[https://github.com/go-oauth2/oauth2] encapsulates golang/oauth2 and could serve as an OAuth server-side.

**Comment by hsluoyz** [comment]
@RobotHuang why is WeChat special? If it is following official OAuth standard, then any one of OAuth servers can support it, right?

**Comment by RobotHuang** [comment]
@hsluoyz I meant that `golang/oauth2` doesn't include `WeChat` endpoint now. I read the source code of `golang/oauth2` and find that it is easy to add other endpoints.

**Comment by hsluoyz** [comment]
@RobotHuang why https://github.com/golang/oauth2 contains OAuth server? It said:

![image](https://user-images.githubusercontent.com/3787410/104615084-d65d9200-56c3-11eb-8ddf-c12ee443913f.png)

**Comment by RobotHuang** [comment]
@hsluoyz Sorry, it is my mistake. It could only be used as client.
