### ISSUE TITLE
Website Reloads on routing

### ISSUE THREAD

**Issue by MehtaManan07** [casbin/casdoor#11]
Everywhere in the project, hrefs are given which reloads the website every time someone navigates. It needs to be corrected and instead, **Links** from **react-router-dom** should be used. 
I am willing to work on the same and few other aspects of the project Casdoor

**Comment by hsluoyz** [comment]
Already fixed by: https://github.com/casbin/casdoor/commit/ee1e08ae209832bf6c32059c04cc0e6cf01eb0f4
