### ISSUE TITLE
I can delete the organazition which related to an application 

### ISSUE THREAD

**Issue by MRGUOKING** [casbin/casdoor#112]
If i have an application which organizition is A . I can delete A directly. After do this,  when I edit the application , it will error.
![image](https://user-images.githubusercontent.com/55344330/122171558-6d688900-ceb2-11eb-8e7b-ed1be663d260.png)
![image](https://user-images.githubusercontent.com/55344330/122171574-735e6a00-ceb2-11eb-94c5-11d037ea6d53.png)

**Comment by MRGUOKING** [comment]
@hsluoyz I will solve this as soon as possible. 
when I delete the organiziton, should I remind the user if there are some applications related to this organizition and delete the applications together？

**Comment by hsluoyz** [comment]
Record applications in the org, do right CRUD, make them consistent.

For UI, gray out the button for orgs with non-empty apps.

**Comment by MRGUOKING** [comment]
@hsluoyz "Record applications in the org, do right CRUD, make them consistent." is the  mean that "add a field to the organization table in database to record the apps of each org"?

**Comment by hsluoyz** [comment]
Yes, add `Applications []string` as a field to org. Remember to update this field in Go backend when app side is updated like app's org update, app rename, app delete.
