### ISSUE TITLE
Add log table and record all user behaviors (signup, signin, logout) into the table, add UI to view logs

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#123]

**Comment by sh1luo** [comment]
What is the database table structure? Put another way, Which fields should be recorded in the database table？

I think there should be `uniq-id(pk)`, `opt-id`, `opt-time`, `source-ip`, `userid`

anything else?

**Comment by hsluoyz** [comment]
@sh1luo I should able to see who did what action at what time. For example, if there's an attacker, the admins should be able to locate the attacks via the logs.

**Comment by oranges-eating** [comment]
I will work for it
