### ISSUE TITLE
frontend bug:unable to display in the Safari browser

### ISSUE THREAD

**Issue by xiaobeiswift** [casbin/casdoor#128]
<img width="2098" alt="image" src="https://user-images.githubusercontent.com/31656300/122962730-47624d80-d3b8-11eb-8d3a-7ca34fe7c80b.png">
<img width="442" alt="image" src="https://user-images.githubusercontent.com/31656300/122962862-6660df80-d3b8-11eb-858b-4fccd228e8f0.png">
<img width="817" alt="image" src="https://user-images.githubusercontent.com/31656300/122963015-7aa4dc80-d3b8-11eb-9468-cd1d1373e730.png">

Unable to display properly in the Safari browser. 
os:Mac 11.4 (20F71),Ios 14.6.
safari version:14.1.1 (16611.2.7.1.4)
ua: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15

**Comment by hsluoyz** [comment]
@Kininaru @sh1luo @oranges-eating

**Comment by hsluoyz** [comment]
I found the faulty code:

https://github.com/casbin/casdoor/blob/1e9cca02fc588029500f9649f7dfdc6cf08805b9/web/src/auth/ForgetPage.js#L302

![image](https://user-images.githubusercontent.com/3787410/123275379-db5a2380-d536-11eb-9579-d7de669f31c2.png)

@sh1luo we need to refactor all the regexes used for Email and phone and put them into Setting.js . We don't need two Email regexes.

**Comment by xiaobeiswift** [comment]
As far as I know, maybe need to change all  /*****/ to  new RegExp("****")

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casdoor/commit/2ba44748c296ffd396533189b13387470f65e18c
