### ISSUE TITLE
Support SAML besides OAuth 2.0

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#140]
See what's SAML: https://www.google.com/search?q=saml+provider

Currently we only support OAuth 2.0 providers, we also need to support SAML.

**Comment by Kininaru** [comment]
Working on this.

**Comment by hsluoyz** [comment]
@sravinet hi! We will add the SAML support soon. Which SAML provider do you use?

**Comment by hsluoyz** [comment]
@seriouszyx please work on this one as next step
