### ISSUE TITLE
Make a Casdoor plugin for Odoo

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#141]
Odoo is a very popular open-source CRM & ERP: https://www.odoo.com/ , written in Python and Javascript.

The source code is: https://github.com/odoo/odoo

We need to develop an "Odoo App" (aka plugin) to let Odoo use Casdoor as SSO. See all available plugins here: https://apps.odoo.com/apps/modules/browse?search=sso

![image](https://user-images.githubusercontent.com/3787410/124340103-6ac19f80-dbe5-11eb-9db3-55528eb208ba.png)

Our plugin will be similar to these two plugins:

1. https://apps.odoo.com/apps/modules/14.0/nexus_okta_sso/
2. https://apps.odoo.com/apps/modules/14.0/nexus_auth0_sso/

See how to develop a Odoo module: https://www.odoo.com/documentation/14.0/developer/howtos/backend.html

**Comment by ffyuanda** [comment]
I'm trying to do this.

**Comment by ffyuanda** [comment]
still working on this:
[Odoo Module](https://apps.odoo.com/apps/modules/14.0/casdoor-odoo-oauth/)
[repo](https://github.com/ffyuanda/casdoor-odoo-oauth)

**Comment by hsluoyz** [comment]
@ffyuanda plz send PR to: https://github.com/casdoor/odoo-casdoor-oauth

The Odoo module name should be: `Casdoor OAuth`

**Comment by ffyuanda** [comment]
@hsluoyz I think we can close this issue for now, and the new repo is created here
https://github.com/casdoor/odoo-casdoor-oauth
