### ISSUE TITLE
Apache Guacamole (Java) as a oidc client receive without nonce

### ISSUE THREAD

**Issue by rwayan** [casbin/casdoor#1469]
guacamole 
Guacamole is an HTML5 web application that provides access to desktop environments using remote desktop protocols (such as VNC or RDP). Guacamole is also the project that produces this web application, and provides an API that drives it. This API can be used to power other similar applications or services.

https://guacamole.apache.org/doc/gug/openid-auth.html

with guacamole.properties setting as below

enable-clipboard-integration: true
extension-priority: openid
openid-authorization-endpoint: http://nas2.example.com:8000/login/oauth/authorize
openid-jwks-endpoint: http://nas2.example.com:8000/.well-known/jwks
openid-issuer: http://nas2.example.com:8000
openid-client-id: b2876c3086f22d23b755
openid-redirect-uri: http://nas2.example.com:18088
openid-username-claim-type: email
openid-groups-claim-type: groups
openid-scope: openid email profile
openid-allowed-clock-skew: 30
openid-max-token-validity: 300
openid-max-nonce-validity: 10

casdoor runs at http://nas2.example.com:8000
guacamole runs at http://nas2.example.com:18088

casdoor application setting shown as below
OAuth grant type is  ID Token
redirect_url is http://nas2.example.com:18088
dingtalk as provider

When open http://nas2.example.com:18088
after finished with dingtalk , will loop in http://nas2.example.com:18088

check logs with guacamole  can see logs as below
17:36:25.698 [http-nio-8080-exec-4] INFO  o.a.g.a.o.t.TokenValidationService - Rejected OpenID token without nonce.
17:37:58.128 [http-nio-8080-exec-8] INFO  o.a.g.a.o.t.TokenValidationService - Rejected OpenID token without nonce.
17:41:36.527 [http-nio-8080-exec-6] INFO  o.a.g.a.o.t.TokenValidationService - Rejected OpenID token without nonce.
17:41:41.977 [http-nio-8080-exec-7] INFO  o.a.g.a.o.t.TokenValidationService - Rejected OpenID token without nonce.
17:51:25.063 [http-nio-8080-exec-2] INFO  o.a.g.a.o.t.TokenValidationService - Rejected OpenID token without nonce.

how can i check if token given with nonce?

**Comment by jakiuncle** [comment]
Hi, can you add my qq 2509913103.  We can communicate on this issue

**Comment by rwayan** [comment]
maybe this patch can fix

diff --git a/controllers/auth.go b/controllers/auth.go
index 6beca02..a0c1954 100644
--- a/controllers/auth.go
+++ b/controllers/auth.go
@@ -99,7 +99,8 @@ func (c *ApiController) HandleLoggedIn(application *object.Application, user *ob
                        resp = &Response{Status: "error", Msg: fmt.Sprintf("error: grant_type: %s is not supported in this application", form.Type), Data: ""}
                } else {
                        scope := c.Input().Get("scope")
-                       token, _ := object.GetTokenByUser(application, user, scope, c.Ctx.Request.Host)
+                       nonce := c.Input().Get("nonce")
+                       token, _ := object.GetTokenByUser(application, user, scope, nonce, c.Ctx.Request.Host)
                        resp = tokenToResponse(token)
                }
        } else if form.Type == ResponseTypeSaml { // saml flow
diff --git a/object/token.go b/object/token.go
index bee14d4..d885f31 100644
--- a/object/token.go
+++ b/object/token.go
@@ -641,9 +641,9 @@ func GetClientCredentialsToken(application *Application, clientSecret string, sc

 // GetTokenByUser
 // Implicit flow
-func GetTokenByUser(application *Application, user *User, scope string, host string) (*Token, error) {
+func GetTokenByUser(application *Application, user *User, scope string, nonce string, host string) (*Token, error) {
        ExtendUserWithRolesAndPermissions(user)
-       accessToken, refreshToken, tokenName, err := generateJwtToken(application, user, "", scope, host)
+       accessToken, refreshToken, tokenName, err := generateJwtToken(application, user, nonce, scope, host)
        if err != nil {
                return nil, err
        }
