### ISSUE TITLE
Act as an OAuth 2.0 + OIDC server

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#15]
Currently, Casdoor uses a home-made logging-in mechanism: https://github.com/casbin/casdoor/blob/master/controllers/account.go

It's not standard and it's unsafe, the password is transmitted over the network.

Finally, we will move to OAuth 2.0 + OIDC. It means that applications like Casbin OA (both JS client and Go backend) will talk to Casdoor via the OAuth 2.0 + OIDC protocols.

We can use: https://github.com/go-oauth2/oauth2 to implement our OAuth 2.0 + OIDC server-side.

The existing code:

- Casdoor JS client SDK: https://github.com/casbin/casbin-oa/tree/master/web/src/auth (currently for agile development, we put the code inside Casbin-OA, so we don't need to publish to NPM then import it in dependency file. In future, when the API is stablized, we will separate the Casdoor JS client code into a new repo and release to NPM)
- Casdoor Go SDK: not available yet, because currently Casbin-OA doesn't involve any server-side code to talk to Casdoor, only client does. This is NOT correct. So we will formulate a Go SDK in the Casbin-OA Go code.

Some reference about this topic: https://github.com/casbin/casdoor/issues/10

**Comment by hsluoyz** [comment]
@RobotHuang

**Comment by sourabhmandal** [comment]
@hsluoyz I would like to work on this

**Comment by sourabhmandal** [comment]
@hsluoyz Hi I am a new contributor to this project. Please tell me how to go about implementing this? I see there is already an oauth2 library being used. And google and github login is being implemented.

**Comment by sourabhmandal** [comment]
are we replacing `golang.org/x/oauth2` [golang oauth2](https://pkg.go.dev/golang.org/x/oauth2)

**Comment by hsluoyz** [comment]
@sourabhmandal generally, we want to support more providers. There's no docs for now as it's developing rapidly. You have to see the code.

**Comment by sourabhmandal** [comment]
@hsluoyz I have created a provider for Facebook. Please review

**Comment by hsluoyz** [comment]
@sourabhmandal can you setup a demo site for testing?

**Comment by sourabhmandal** [comment]
@hsluoyz 👍 sure, working on it

**Comment by sourabhmandal** [comment]
@hsluoyz do you want me to build a site from scratch or use the existing code in `/web` directory.

**Comment by LeonDevLifeLog** [comment]
why close this issue? @hsluoyz

**Comment by hsluoyz** [comment]
@LeonDevLifeLog because this issue has been done (completed). Casdoor has fully supported OAuth 2.0 and OIDC now. The server side is this repo. The client SDKs can be found at: https://github.com/casdoor

**Comment by LeonDevLifeLog** [comment]
i see. thanks
