### ISSUE TITLE
Translation regression for the "Sync from crowdin" commit

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#158]
Some Chinese translations are removed by the commit: https://github.com/casbin/casdoor/commit/576d0f12dd5dc408991814de642ab0046ccf58b4

![image](https://user-images.githubusercontent.com/3787410/125111958-22403f80-e119-11eb-8725-caaa41408e2b.png)

Also, don't use my account for these commits:

![image](https://user-images.githubusercontent.com/3787410/125112006-31bf8880-e119-11eb-988e-7bd85df9ee60.png)

**Comment by hsluoyz** [comment]
@ErikQQY

**Comment by ErikQQY** [comment]
Got it, working on it
