### ISSUE TITLE
Use a select for the language selection

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#165]
Showing all languages here are not good-looking. Change it to a select.

![image](https://user-images.githubusercontent.com/3787410/125458474-0972276f-af8f-4c94-bd00-f6298a6a6941.png)

**Comment by ErikQQY** [comment]
Working on this issue.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casdoor/pull/175
