### ISSUE TITLE
Sign up email code problem

### ISSUE THREAD

**Issue by ffyuanda** [casbin/casdoor#166]
I'm trying to sign up for the website but after I received the email code this is shown:
![image](https://user-images.githubusercontent.com/46557895/125558528-c4a0802a-5d9a-4462-9671-be37fa8dc5a2.png)

**Comment by sh1luo** [comment]
@ffyuanda Hi, see backend log plz

**Comment by hsluoyz** [comment]
@sh1luo plz help him setup the environment, report bugs if there are any.

**Comment by hsluoyz** [comment]
@ffyuanda any update?

**Comment by ffyuanda** [comment]
@hsluoyz I'm setting up the database and try to see if there is anything weird in it...

**Comment by ffyuanda** [comment]
Since the problem cannot be reproduced for now, I will close the issue.
