### ISSUE TITLE
Creat API to get backend data for homepage to show

### ISSUE THREAD

**Issue by turbodog03** [casbin/casdoor#167]
## Such as 
* the number of authorization, new user,  new registion within a time (like 7days)
* Total user number
* the time of logging in actions 
* and so on.

So that we can show these data on our homepage

**Comment by WindSpiritSR** [comment]
Working on it～

**Comment by hsluoyz** [comment]
@WindSpiritSR no need to hurry up for this issue now. I think @turbodog03 proposed this issue just for himself to track his own status. So this issue should be left to him to finish. To avoid misunderstanding, I'm closing this issue here.
