### ISSUE TITLE
Translation hot reload

### ISSUE THREAD

**Issue by ErikQQY** [casbin/casdoor#168]
Casdoor is using i18next as our internationalization tool, every time we want to change to other language, we click the button and Casdoor will refresh the page and load the language we want, however, I think using hot reload might be more elegant and suitable.

Since Casdoor is based on React, I think [react-i18next](https://react.i18next.com/) can help us achieve that feature.

A react-i18next based demo: https://codesandbox.io/s/1zxox032q

More details:
https://github.com/i18next/react-i18next
https://dev.to/adrai/how-to-properly-internationalize-a-react-application-using-i18next-3hdb

**Comment by hsluoyz** [comment]
Hot reload will bring the `[object object]` bug, see: https://github.com/casbin/casdoor/pull/169#issuecomment-881206568

And I don't think removing refresh is good, because changing language is very low-frequency operation, and the users need feedback like page refresh.

So closed here for now.
