### ISSUE TITLE
Add a self check at the beginning of the program

### ISSUE THREAD

**Issue by Kininaru** [casbin/casdoor#170]
Sometimes the JavaScript front end will crash because some `undefined` or `null` values. This is because back end databases have some `null` values. I think we can add a self check to remove illegal data from the database.

**Comment by hsluoyz** [comment]
@Kininaru example?

**Comment by Kininaru** [comment]
@hsluoyz 

Like this: 
![image](https://user-images.githubusercontent.com/42638489/125781334-852d96aa-56e9-4753-bec9-7dd3eb4ead72.png)

For this example, JS crashed because of a null value in database:
![image](https://user-images.githubusercontent.com/42638489/125781470-d77d8bdd-305a-43bc-a4be-0c5577a4febf.png)

Add a self check to fix all these null values.

**Comment by hsluoyz** [comment]
@Kininaru we should init the correct data in DB, instead of fixing corrupted DB data at run time.
