### ISSUE TITLE
Need event system in order to update user data in client real-timely

### ISSUE THREAD

**Issue by hyperzlib** [casbin/casdoor#173]
Refer to ucenter and keycloak, when user change their profile or credentials, an event will emitted to Client over HTTP or MQTT.
I think there needs to be an event system like EventEmitter (which is system library of Node.js) so that developers can subscribe events and realize event push feature.

**Comment by hsluoyz** [comment]
@sh1luo

**Comment by sh1luo** [comment]
ok, I will continue to follow up on this issue

**Comment by hsluoyz** [comment]
@sh1luo this will be the 1st priority for you now.

**Comment by hsluoyz** [comment]
Done by: https://github.com/casbin/casdoor/commit/30a2fdef372d3f0414dff0bb8510828b434cb2f5
