### ISSUE TITLE
The translation is broken

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#176]
When translating to Chinese, only "Home" is translated.

Demo site: http://39.106.18.82/

![image](https://user-images.githubusercontent.com/3787410/126021188-f2b8c96a-d02f-4274-85fe-f2d8d31883f4.png)

**Comment by hsluoyz** [comment]
@ErikQQY

**Comment by ErikQQY** [comment]
I think it is because there was a wrong commit https://github.com/casbin/casdoor/commit/2297251dd7523892983ce46d3289a45f597828be

The latest commit is working fine https://github.com/casbin/casdoor/commit/3905df854644567f706013729338de6209603259

**Comment by ErikQQY** [comment]
I noticed that wrong commit clear all of the data on crowdin, I am investigating why there are wrong commits.

**Comment by hsluoyz** [comment]
@ErikQQY good found. Plz investigate this bug ASAP.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casdoor/commit/07178a7125db5083a7e32cb0dd194d30bbeb73c6
