### ISSUE TITLE
Empty alert message in forget page

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#178]
http://testb.rescld.cn/forget

When inputing the verification code wrong, the alert is empty.

![image](https://user-images.githubusercontent.com/3787410/126055483-da326a2c-38d9-475a-8e49-8c0ce1a53edc.png)

**Comment by hsluoyz** [comment]
@sh1luo

**Comment by sh1luo** [comment]
ok, I will resolve these issues in the next commit.

**Comment by hsluoyz** [comment]
@sh1luo plz make a PR for fixing this bug.

**Comment by sh1luo** [comment]
@hsluoyz ok

**Comment by sh1luo** [comment]
@hsluoyz I will take the last exam of this semester at 2 o’clock tomorrow afternoon, and I will complete this issue and pr 2fa after the end.

I'm almost done right now 🥂

**Comment by sh1luo** [comment]
@hsluoyz 
![image](https://user-images.githubusercontent.com/51157931/126453980-e8510639-bf21-4502-a85e-55416c8009dc.png)

I did not reproduce this problem

**Comment by hsluoyz** [comment]
I can't reproduce it either now. Closed.
