### ISSUE TITLE
Support uploading and tailoring user's avatar image

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#18]
See: https://forum.casbin.com/t/91

In future, Casbin-forum will use Casdoor as authentication and user management, so I think we will manage the user avatar in the scope of Casdoor.

For where to store the uploaded avatar image, we can use this: https://github.com/qor/oss to provide support for multiple OSS providers.

**Comment by Kininaru** [comment]
Working on this.

**Comment by Kininaru** [comment]
Project in my branch has been deployed at https://door-hk.chromium.link. 
Click "My Account - Upload Avatar" to tailoring and uploading an avatar.

**Comment by nafees87n** [comment]
Hi @hsluoyz 
Is this issue open?
I am new to casbin and want to contribute to it. Currently, I am going through the codebase. Can you please provide me with some resources to understand how to start with this issue?

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casdoor/issues/18
