### ISSUE TITLE
3rd-party login's style is broken in mobile view

### ISSUE THREAD

**Issue by ErikQQY** [casbin/casdoor#193]
When we log in casdoor using mobile phone, the account config does't display well.

Tested on iOS 14.4.2 and Android 4.14.116, both have the same bug.

See: https://door.casbin.com/account

![image](https://user-images.githubusercontent.com/3787410/126874600-0923513b-4283-4e2e-8bcf-19456ad60d17.png)

**Comment by hsluoyz** [comment]
@turbodog03

**Comment by turbodog03** [comment]
working on this
