### ISSUE TITLE
A suggestion for README.md

### ISSUE THREAD

**Issue by Kininaru** [casbin/casdoor#20]
Should we tell our users in the paragraph `Installation` to proxy the URL `https://(hostname)/api/` to `http://localhost:8000` in their servers?

**Comment by hsluoyz** [comment]
Why? The Go code in port 8000 already listens to /api/* requests.

**Comment by Kininaru** [comment]
@hsluoyz 

I would like to say my opinion:

Here's all the code about `ServerUrl` in Setting.js:

```javascript
const hostname = window.location.hostname;
if (hostname === "localhost") {
    ServerUrl = `http://${hostname}:8000`;
}
```

if the server is not running locally, the value of `ServerUrl` will be empty, and webpages will request info from the port on which front-end is listening. However, the front-end port is not the same as the back-end port, so there may be an error.

And there is another case: To hide the port in browsers, I used nginx proxy_pass. If I don't configure it specially, API requests will also be received by the front-end incorrectly.

**Comment by hsluoyz** [comment]
@Kininaru this is a usage of myself:

1. Dev: I use localhost, start backend at 8000, start frontend at 7001. The frontend will auto-refresh.
2. Prod: I use Nginx as a reverse proxy to hold domain name, SSL, etc. The traffic is redirected to backend's 8000. The frontend is built into static files and also served by Go backend (see the Go code about the static serving logic).

I don't know if this is the best practice but it's very convenient to me. Maybe we should document this usage clearer in the README.

**Comment by Kininaru** [comment]
@hsluoyz 

Got that. Can I commit something about this in the README?

**Comment by hsluoyz** [comment]
You can send PR.
