### ISSUE TITLE
Duplicate `save` button

### ISSUE THREAD

**Issue by Zxilly** [casbin/casdoor#204]
When I log in `https://door.casbin.com/account`, it shows 2 `save` button.
![image](https://user-images.githubusercontent.com/31370133/127255049-27377d35-9b5a-49ca-82b9-a66543238a0d.png)
![image](https://user-images.githubusercontent.com/31370133/127255069-49557da2-c98c-4ed6-a1bb-7d9dddefbfe5.png)

And `https://gsoc.casbin.org/` is also not available. It asks me to update my display name endless.
![image](https://user-images.githubusercontent.com/31370133/127255124-3b247c8f-0245-4887-ad2e-ba813b81cb36.png)
@Kininaru

**Comment by Kininaru** [comment]
@Zxilly Everything is ok on `https://gsoc.casbin.org` . The alert won't show if you update your real name.

**Comment by Kininaru** [comment]
@Zxilly I think 2 save buttons are needed. That is convenient.
