### ISSUE TITLE
Can't get the correct IP if using a proxy

### ISSUE THREAD

**Issue by denymz** [casbin/casdoor#206]
https://github.com/casbin/casdoor/blob/512a451800864fd3cead085da1becaf134142bbe/controllers/verification.go#L43-L44

The above code does not handle the use of proxies, resulting in the IP recorded in the database being the IP of the proxy server

**Comment by hsluoyz** [comment]
@denymz I think it already extracts the the real-IP from RemoteAddr, doesn't it work? So what proxy are you using? Or better if you could send a PR.

**Comment by hsluoyz** [comment]
@Kininaru @sh1luo

**Comment by denymz** [comment]
> @denymz I think it already extracts the the real-IP from RemoteAddr, doesn't it work? So what proxy are you using? Or better if you could send a PR.

Should first try to get from 'X-Forwarded-For' or 'X-Real-IP' header
It should be handled like this
https://github.com/casbin/casdoor/blob/512a451800864fd3cead085da1becaf134142bbe/util/record.go#L33
https://github.com/casbin/casdoor/blob/512a451800864fd3cead085da1becaf134142bbe/util/log.go#L47-L49

**Comment by hsluoyz** [comment]
@denymz can you make a PR?

**Comment by Kininaru** [comment]
Maybe you need to pass some http headers in your proxy server?

**Comment by Kininaru** [comment]
For Casdoor itself, it cannot get the exact remote IP, because requests to Casdoor is made by proxy servers like nginx. So we can't solve this problem by modifying Casdoor. Instead, we should modify nginx.conf to pass the information of remote.

**Comment by hsluoyz** [comment]
@denymz fixed by: https://github.com/casbin/casdoor/commit/f87cdf6cff0753323ed5420322cc67fe0d479e1e
