### ISSUE TITLE
Duplicate key cause table errors

### ISSUE THREAD

**Issue by WindSpiritSR** [casbin/casdoor#210]
https://user-images.githubusercontent.com/24910914/127731784-a619ee85-2695-41a0-8347-58ac379e42a9.mp4

**All key-based components may occur this problem.**

This error cause we use the wrong or duplicate `rowKey` to build a table, every time we click the `Add` button, it generates a row like

```json
{
    "key": "Please select a signup item",
    "value": "..."
}
```

I fixed part of the errors in `web/src/UrlTable.js`: [`860fe91`](https://github.com/casbin/casdoor/commit/860fe91725865f202c2e282fe956647a6d4674f8#diff-aa513e39552689c307c054b430526e17ef206f1db173d3cb4c3705ee20d3d1abL98-R98)

**Comment by hsluoyz** [comment]
@WindSpiritSR plz fix it in other places.
