### ISSUE TITLE
Can you specify the default login method?

### ISSUE THREAD

**Issue by learning-go123** [casbin/casdoor#222]
Like in the picture below
![image](https://user-images.githubusercontent.com/88469563/128281825-44903bae-2a12-4477-88b0-bc2f6434d77b.png)
The QR code can be displayed directly on the login page

Should add a column "Default" to the providers table. Only one provider can set it to "true", then the login page will automatically redirect to this provider's OAuth page without clicking the OAuth buttons.

![ULF@@III}OID8D@ATN2KXAP](https://user-images.githubusercontent.com/3787410/128282089-7a5f26e2-a9f8-470b-8fa4-772a2ec49f38.png)

**Comment by hsluoyz** [comment]
@WindSpiritSR

**Comment by WindSpiritSR** [comment]
Working on it

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casdoor/commit/bbb6c839df98a61a539db43797fcc7f2a2ef522e
