### ISSUE TITLE
need to show 404 page

### ISSUE THREAD

**Issue by sh1luo** [casbin/casdoor#223]
Casdoor should display 404 page when the user visits a path that does not exist.

But now, just blank, I think it's a bit unfriendly. The user may not know what is happening now causing the blank page, its own error or something else?

![image](https://user-images.githubusercontent.com/51157931/128286397-9857a068-3920-4890-8a01-b60431c03c4b.png)

**Comment by hsluoyz** [comment]
@sh1luo good, plz do it.

**Comment by sh1luo** [comment]
> @sh1luo good, plz do it.

ok, work on it.
