### ISSUE TITLE
 Set password input times and password reset time

### ISSUE THREAD

**Issue by WarlockFish** [casbin/casdoor#2272]
At present, I have not found the number of password inputs and password reset time. 

I debugging the code，and  intentionally entering the wrong password ， I need to reset and  put password again  after15 minutes. How should I set the reset password OR hope directly set the password input frequency and reset time on the application interface

_Originally posted by @WarlockFish in https://github.com/casdoor/casdoor/discussions/2254_

**Comment by HGZ-20** [comment]
The code below shows the handling of incorrect passwords.
https://github.com/casbin/casdoor/blob/4eb725d47a5e3212180d43cdb4ae3c67ad65cccd/object/check.go#L30-L33
https://github.com/casbin/casdoor/blob/4eb725d47a5e3212180d43cdb4ae3c67ad65cccd/object/check.go#L145-L164

The current limitations on the number of incorrect password attempts and the retry time are hard-coded in the code. Currently, dynamic changes are not supported. If you have a requirement for modifications, you may need to directly modify the code.
