### ISSUE TITLE
Support to upload avatar image with more formats (.bmp, .jpg, .tiff, etc.) instead of .png only

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#232]
![image](https://user-images.githubusercontent.com/3787410/128542964-08e1841f-6ff4-4a42-84de-43079195f3e3.png)

**Comment by hsluoyz** [comment]
@WindSpiritSR @sh1luo @oranges-eating

**Comment by sh1luo** [comment]
@hsluoyz Seems to have been resolved.

**Comment by prsndp** [comment]
Hi @hsluoyz Can I work on this issue as a contributor?

**Comment by hsluoyz** [comment]
@prsndp sure!

**Comment by hsluoyz** [comment]
Already done.
