### ISSUE TITLE
Prebuilt docker image from a registry

### ISSUE THREAD

**Issue by SchoolGuy** [casbin/casdoor#234]
As a server admin I would not like to build an application for myself but would like to consume a finished image. This would make it much easier to deploy the application.

The most known registry I know is Docker Hub where it should be easy to integrate an automatic rebuilt of the image on certain conditions. Also possible would be the Container Registry from GitHub.

**Comment by sh1luo** [comment]
@SchoolGuy ok, We can publish image to dockerhub so that it can be directly pulled by `docker pull`

**Comment by SchoolGuy** [comment]
@sh1luo Thanks a lot!

**Comment by hsluoyz** [comment]
@sh1luo plz finish this issue: https://github.com/casbin/casdoor/issues/235 first, so we can have CI and version to push to DockerHub.

**Comment by sh1luo** [comment]
@SchoolGuy I have released an early preview version on my dockerhub personal account, you can experience it. After waiting for the review to pass, the formal image will enter the dockerhub official warehouse of casbin 🥂 🥂 🥂 🥂 

![image](https://user-images.githubusercontent.com/51157931/128823743-c920776c-d2ec-4e79-9562-cd97c9aed12f.png)

**Comment by SchoolGuy** [comment]
@sh1luo I will test it on the Weekend!

**Comment by sh1luo** [comment]
> @sh1luo I will test it on the Weekend!

No problem 🥂

**Comment by SchoolGuy** [comment]
I saw that a `casbin` Account has also published casdoor. I will use that one right now. By the end of my day I think I will be able to confirm that this is working as expected.

**Comment by sh1luo** [comment]
@SchoolGuy Hi, although we have released the casdoor image to dockerhub, this is only the application itself, in addition to the mysql database, you still need to pull a mysql image through `docker pull` first, and then execute `docker run --link mysql:db ...` ,which can connect the casdoor image and the mysql image. It might be a little difficult for you.

There is another way that may be more suitable for you, first clone the entire casdoor project, and then execute `docker-compose up`

```bash
git clone https://github.com/casbin/casdoor.git
cd casdoor && docker-compose up
```

**Comment by SchoolGuy** [comment]
@sh1luo Yes I was aware of that. I am not quite far with my webapp but I got the web frontend of casdoor running in my own compose. So from my side this issue can be closed. If you don't have any tasks internally please close the issue yourself. Thanks for the quick help! :)

**Comment by hsluoyz** [comment]
Great to hear!
