### ISSUE TITLE
Question: Multitenant web-app uses casdoor

### ISSUE THREAD

**Issue by HRNasr** [casbin/casdoor#2359]
I am in the project of writing a multi-tenant program for different people with different applications in casdoor (The url addresses of users are different from each other in this project   people*.pay.com).

 Is there a project or example that has been used by someone far away in this situation? Please help me.

**Comment by bigbang4u2** [comment]
Any update on this?

**Comment by hsluoyz** [comment]
@HRNasr see Casibase: https://github.com/casibase/casibase or Casvisor: https://github.com/casbin/casvisor
