### ISSUE TITLE
Allow dynamic modification of the JWT (e.g. with GraphQL)

### ISSUE THREAD

**Issue by boris-donchev** [casbin/casdoor#2375]
Currently as far as I see there is no way to modify which fields are included in the JSON Web Token. 

There are only 2 options: 
  - JWT
  - JWT-Empty
https://casdoor.org/de/docs/token/overview/

What I am looking for is a way to reduce the volume of the JWT, but still retain some fields.

E.g. - I want to see the permissions for a user, but not which users have the same permissions.

Suggestion: Use GraphQL to create the query for the Token. Something like Hasura's solution, or even a plain Text solution will be perfect!

https://hasura.io/blog/content/images/2021/03/Screen-Shot-2021-03-10-at-5.24.58-PM-1.png

**Comment by hsluoyz** [comment]
@boris-donchev fixed by: https://github.com/casbin/casdoor/commit/b118a3bb762d49d3a39c3695daaf25a95d854c42 and https://github.com/casbin/casdoor/commit/a2b9f9baaf9a3830494e594ed9d4ee83c9fb6357

"JWT-Custom" option is added to support customizing user properties inside access token
