### ISSUE TITLE
Use HttpRouter instead of beego

### ISSUE THREAD

**Issue by sourabhmandal** [casbin/casdoor#24]
@hsluoyz If we could use HttpRouters in this project, owing to the fact that HttpRouter outperforms Beego in terms of performance and memory usage.
I would give just a minor performance boost but I think it's worth it as the project grows.

[benchmark of different go-routers](https://github.com/julienschmidt/go-http-routing-benchmark)

**Comment by hsluoyz** [comment]
Don't do BIG refactoring as a new contributor. Please add features to make it work first.
