### ISSUE TITLE
Some issues regarding default groups and third-party login

### ISSUE THREAD

**Issue by 861662865** [casbin/casdoor#2417]
How to specify that newly registered users are bound to a group by default

Unregistered users who use third-party login will not jump to the registered user page, but will directly jump to the application's homepage page

After enabling the post registration reminder binding function, it will not jump to the user's binding page, but will directly jump to the error page

Can the data in the token and session menus be automatically deleted after expiration or logout

Could you please provide guidance? Thank you very much

**Comment by hsluoyz** [comment]
@861662865 provide:

1. Your application edit page setting
2. Demo video
3. Live site URL

**Comment by 861662865** [comment]
![conf](https://github.com/casdoor/casdoor/assets/147549735/3581bbdd-ccf6-4d2a-90a2-4063ce25b7ec)


https://github.com/casdoor/casdoor/assets/147549735/3a85e1e8-bcea-4cb4-bfdf-ffdb1350a822


https://github.com/casdoor/casdoor/assets/147549735/16262d48-671e-4e75-82ae-f2b6f10230b1


https://github.com/casdoor/casdoor/assets/147549735/70b74aac-fb2b-4281-8a20-07d0a677035b

https://pan.402-nas.top:1000/


Thank you

**Comment by 861662865** [comment]
[file.zip](https://github.com/casdoor/casdoor/files/13058425/file.zip)
There seems to be some issues with the video, so a compressed package was used. Please review it. Thank you
