### ISSUE TITLE
Different response format at batch-enforce method

### ISSUE THREAD

**Issue by dplynskiy** [casbin/casdoor#2420]
hi,

when using enforceId param - i get bool array
when using modelId param - i get array of bool arrays 

BatchEnforce method return bool array for each adapter linked with model, but it is useless anyway until u can't assign arrays in response with adapters (order of arrays by adapter is unknown for caller side). So really it can be used only when I have only one adapter

I think method should always return bool array, and probably it should return error if we have more than 1 adapter for modelId

What do you think about it?

**Comment by hsluoyz** [comment]
ping @notdu for PR: https://github.com/casdoor/casdoor/pull/2009

**Comment by notdu** [comment]
hi @dplynskiy,
i think you are right, but `it should return error if we have more than 1 adapter for modelId` not make sense, this is Casdoor's feature should support multi adapter per model, how about response array of adapter (the same order with []bool result) in resp.Data2

**Comment by notdu** [comment]
Or i will flatten the array, it will always return bool array
how do you think @hsluoyz

**Comment by hsluoyz** [comment]
@dplynskiy @notdu fixed by: https://github.com/casbin/casdoor/commit/a42594859fa3cfe72532a071a46357d6da8bb974
