### ISSUE TITLE
Add "Files" to navbar to manage all uploaded files including avatar and terms

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#243]
![image](https://user-images.githubusercontent.com/3787410/128800439-5ad3262b-eb01-48fa-b831-4a1d42b74b80.png)

**Comment by hsluoyz** [comment]
@WindSpiritSR

**Comment by WindSpiritSR** [comment]
Working on it

**Comment by hsluoyz** [comment]
Done.
