### ISSUE TITLE
feature: add user agreement to login page too

### ISSUE THREAD

**Issue by werewolf666** [casbin/casdoor#2442]
How does the web login UI of casdoor add user protocols? Nowadays, mobile devices require users to agree to the user agreement before logging in, and it seems that our cashdoor only has a registration pag.

login :
<img width="353" alt="30621e914bd1692fc27afe86de19939" src="https://github.com/casdoor/casdoor/assets/35163330/29d593c3-80c7-449c-ac80-65171c39a2fd">

sign up:
<img width="318" alt="5fe6eed8ecf643d4e19721427ab831e" src="https://github.com/casdoor/casdoor/assets/35163330/ab4036d2-5e8d-47ab-a049-7707961c13b6">

**Comment by hsluoyz** [comment]
@werewolf666 this feature already exists, choose `Signin` rule in the "Agreement" row of "Signup items" table

![_WQVLP_$B{{H`)$L3J7S%8X](https://github.com/casbin/casdoor/assets/3787410/0ec9dc54-be85-4a05-bfd3-b44c454a4ae2)

![image](https://github.com/casbin/casdoor/assets/3787410/2402a6ad-dd8e-421a-b436-f4a45cb3c0b1)
