### ISSUE TITLE
The api/get-user interface is error

### ISSUE THREAD

**Issue by kinglinglive** [casbin/casdoor#2489]
version：1.451
![image](https://github.com/casbin/casdoor/assets/134067384/2ac64422-f27e-40ac-9f7a-ff0c2b7f98c7)
![image](https://github.com/casbin/casdoor/assets/134067384/ffaa3d83-1eb1-47e5-9c89-f57c80d40dd2)

**Comment by hsluoyz** [comment]
http://localhost:8000/api/get-user?id=<org_name>/<user_name>
