### ISSUE TITLE
how  to change the bits of a cert ?

### ISSUE THREAD

**Issue by karl-chanel** [casbin/casdoor#2490]
![屏幕截图 2023-11-12 152518](https://github.com/casbin/casdoor/assets/78248702/dce8e786-014b-42b9-b8e0-1e4c601d16b3)
when i change the bits from 4096 to 2048 in the ui, will it take effect?

**Comment by hsluoyz** [comment]
@karl-chanel yes

![image](https://github.com/casbin/casdoor/assets/3787410/eb399e68-fa3e-4256-81d5-6b5e09f182aa)

**Comment by karl-chanel** [comment]
The reason I want to change bits to 2048 is that when im using apisix oidc plugin it'll generate a really big session ,i think it's related to the cert bits , because when i tried with authing(another idp) with apisix with a cert of 2048 bit , the session size reduced a lot

**Comment by karl-chanel** [comment]
It doesn't seems to take effect when i change it 2048 ,when i click save, i didn't see any change in the public or the private key.

**Comment by karl-chanel** [comment]
> @karl-chanel yes
> 
> ![image](https://github.com/casbin/casdoor/assets/3787410/eb399e68-fa3e-4256-81d5-6b5e09f182aa)
> 

我点击添加证书，它会默认生成一个4096的证书，我改变这个位数它会重新生成吗？

**Comment by karl-chanel** [comment]
> > @karl-chanel yes
> > 
> > ![image](https://github.com/casbin/casdoor/assets/3787410/eb399e68-fa3e-4256-81d5-6b5e09f182aa)
> > 
> 
> 我点击添加证书，它会默认生成一个4096的证书，我改变这个位数它会重新生成吗？

could u reopen the issue ,change the bit of the cert in the ui will not trigger a update of the existing cert, I think it's a bug.@hsluoyz

**Comment by hsluoyz** [comment]
@karl-chanel fixed by: https://github.com/casbin/casdoor/commit/5b151f4ec4d74432ac4189e470e454204e7eb2d5
