### ISSUE TITLE
bug when i use a 1024 bit cert

### ISSUE THREAD

**Issue by karl-chanel** [casbin/casdoor#2491]
![屏幕截图 2023-11-12 163516](https://github.com/casbin/casdoor/assets/78248702/8bed612a-6e42-4317-9918-711cfdc5ee94)
when i try to generate a 1024 bit cert by my self , and copy it to the ui , then jwks endpoits prints above , and i tried 2048 bit cert ,it works fine

**Comment by hsluoyz** [comment]
@karl-chanel why close?

**Comment by karl-chanel** [comment]
it's not casdoor's fault,i copy the generated key with an extra  character "/n"
