### ISSUE TITLE
Single app associated with multiple organization

### ISSUE THREAD

**Issue by bigbang4u2** [casbin/casdoor#2497]
Basically what we have single sass application and we would like to onboard organization (will have its own users) to our app. At login they should be able to choose or enter organization in which they want to login and then provide user name password.

I checked casdoor and it seems like right now one application can belong to only one organization.
How can I achieve above using casdoor.
Do I need to create multiple applications
e.g
app1-org1
app1-org2
app1-org3

It would be easier if I can have only single app and would be able to associate multiple organization to it

**Comment by bigbang4u2** [comment]
@hsluoyz Any updates on this?

**Comment by hsluoyz** [comment]
@bigbang4u2 you can change `Org choice mode` in application edit page to `Select` or `Input` values to enable multi-organization login for an application for a SaaS scenario, see docs at: https://casdoor.org/docs/application/specify-login-organization

**Comment by bigbang4u2** [comment]
> @bigbang4u2 you can change `Org choice mode` in application edit page to `Select` or `Input` values to enable multi-organization login for an application for a SaaS scenario, see docs at: https://casdoor.org/docs/application/specify-login-organization

I exactly tried this but then I get 404 not found at the time of login saying

`The application does not exist`
I created two organization
1. org1
2. org2

For built-in application I enabled org select mode
Now as soon as I select an organization at time of login it throws error `The application does not exist`

**Comment by hsluoyz** [comment]
@bigbang4u2 for each organization that shows up in the org select menu, you need to make sure it has at least one application and set it in the `Default application` field of the organization edit page like: https://door.casdoor.com/organizations/built-in

This is because the login page data (like the login page's logo, whether to enable password, whether to enable Google OAuth login, etc.) are stored in the application object. So an organization without any application doesn't know how to render the login page

![image](https://github.com/casbin/casdoor/assets/3787410/8f12f001-86e1-408a-b88f-36529031c002)

**Comment by bigbang4u2** [comment]
@hsluoyz Thanks for update, I looked at it and it seems like one can only select single application in there. What if I have multiple applications which I want to associate with a single org. You mentioned `at least one application and set it in the Default application`. Is there a way to associate multiple applications ?

**Comment by hsluoyz** [comment]
Org and App are 1 : N, see: https://casdoor.org/docs/basic/core-concepts

**Comment by bigbang4u2** [comment]
@hsluoyz My question is where to assign multiple apps to a particular org. I could not find a way in UI to do that

**Comment by bigbang4u2** [comment]
@hsluoyz Could you please let me know how I can assign multiple apps to single org. As of now I only see default application in an org where I can only select one org
