### ISSUE TITLE
Update Docs for go get command

### ISSUE THREAD

**Issue by sourabhmandal** [casbin/casdoor#25]
@hsluoyz This is the error I faced
![image](https://user-images.githubusercontent.com/39632788/111484739-07a61d00-875c-11eb-88b3-e4292f68a727.png)

On using `go get github.com/casdoor/casdoor` I got this.
![image](https://user-images.githubusercontent.com/39632788/111485048-4c31b880-875c-11eb-9452-5f44b5aff0f2.png)

Seems like the package is not registered.

**Comment by hsluoyz** [comment]
@sourabhmandal use:

go get github.com/casbin/casdoor
