### ISSUE TITLE
[Problem] Setting multiple permissions based on different roles for the same application can result in login failure

### ISSUE THREAD

**Issue by qq1176914912** [casbin/casdoor#2502]
I have set up two roles for the same organization in the role, one for HR and one for admin
![image](https://github.com/casbin/casdoor/assets/79817742/66bdaf62-3b6e-44e7-b4e6-0e70b7947e17)
And two policies have been configured in the permissions: hr has read permission, and admin has all permissions
![image](https://github.com/casbin/casdoor/assets/79817742/bede794e-b750-4bb8-a18c-fa7f6f415561)
When both permissions are enabled, the login of both users with configured permissions displays unauthorized operations
![image](https://github.com/casbin/casdoor/assets/79817742/a23e38af-5599-4abe-bd4e-4c436fea3563)
Only when one permission is closed can another account operate. Is it just the design or a bug?

**Comment by hsluoyz** [comment]
@qq1176914912 tested with no issue. Make sure the application is correct. You can debug `CheckLoginPermission` function
