### ISSUE TITLE
pq: value too long for type character varying(500) on use login

### ISSUE THREAD

**Issue by arren-ru** [casbin/casdoor#2503]
We got issue running version 1.275, but after upgrading to 1.454, issue still not gone.
After a little research discovered that avatar url is a little bit longer its corresponding column 😄 to be saved to.
So as temporary fix I've changed type to text to eliminate data limit.

Issue is similar to #1795  but for user data.
Problem url was sent during google auth.

**Comment by hsluoyz** [comment]
@arren-ru `varchar(500)` is definitely enough for all normal use cases. Will not change it.
