### ISSUE TITLE
providers  aliyun sms test send error

### ISSUE THREAD

**Issue by liuyangyi** [casbin/casdoor#2527]
![1701854726233](https://github.com/casbin/casdoor/assets/9301481/b7a7503c-114c-4468-8933-89500799e9ad)

As shown in the above figure
select providers aliyun sms test send code  response  status error
but there is no other error prompt
 there are  check Client ID Client secret and Template code  all right
please help me

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/go-sms-sender/commit/f6dc61ae9e4b46ff46368868114cb705366f1115 and https://github.com/casbin/casdoor/commit/5521962e0c96e9a6e4266f5384531eda5a1b33c9

**Comment by liuyangyi** [comment]
think you
