### ISSUE TITLE
Cannot get API key generation for user

### ISSUE THREAD

**Issue by vincent-pli** [casbin/casdoor#2529]
I notice #1971 and seems it has been merged in 1.337.0,
I installed `v1.457.0`, but cannot see the feature in user page,

That's the snap shot of video from #1971:
<img width="794" alt="image" src="https://github.com/casbin/casdoor/assets/8669744/a9398140-ec0a-4de0-b0de-d897f10b7c28">

but there is no `API key` section with version `v1.457.0`, anything I missing?

**Comment by hsluoyz** [comment]
@vincent-pli enable the `API key` property in organization edit page like: https://door.casdoor.com/organizations/built-in

See docs at: https://casdoor.org/docs/organization/accountCustomization/

![image](https://github.com/casbin/casdoor/assets/3787410/7beaa643-77a9-4385-bf38-bb922a1304a7)

**Comment by vincent-pli** [comment]
Great, thanks
