### ISSUE TITLE
POST method not work using HTTP SMS Provider, phone number did not pass correctly

### ISSUE THREAD

**Issue by tutugreen** [casbin/casdoor#2535]
Using Version: 
casbin/casdoor:latest
IMAGE ID: 3b56fd912350

Phone number parms seemes not pass correctly when choose POST method.

It works when using GET.

The phone number can be found in query string.

The code can be found both in query string and body, don't know why it appear in body.

![GET](https://github.com/casbin/casdoor/assets/7879628/cb553945-448b-4109-b41f-3d0ea8bfed1a)

When using POST,
could not found phone number in query string nor post body.
found code in body.

![POST](https://github.com/casbin/casdoor/assets/7879628/ce103978-3f3d-4ddb-85b7-1a4161550be3)

**Comment by tutugreen** [comment]
seems in code, regardless of whether it's a GET or POST request, the request is created with a body:

https://github.com/casbin/casdoor/blob/dc06eb99485631087ba98ab644cc7c9fbc774ca8/notification/custom_http.go#L46

also happens in the notification, the param Name not function with post, the message passed as a form key

![image](https://github.com/casbin/casdoor/assets/7879628/cc3a8afe-57a3-404a-87b3-4546a8b3e825)

https://github.com/casbin/casdoor/blob/dc06eb99485631087ba98ab644cc7c9fbc774ca8/notification/custom_http.go#L46


maybe use 

`req, err := http.NewRequest(c.method, c.endpoint, nil)`

instead?

too late, will build&test tomorrow.

**Comment by hsluoyz** [comment]
@tutugreen Which provider category are you using? Notification or SMS?

**Comment by hsluoyz** [comment]
The SMS has the parameter:

![image](https://github.com/casbin/casdoor/assets/3787410/0500cf92-5963-48ca-aa09-6ffdd8b46da9)

**Comment by tutugreen** [comment]
Just tested, this happens in both Custom HTTP SMS Provider & Custom HTTP Notification Provider.

![2023-12-14-N-2](https://github.com/casbin/casdoor/assets/7879628/f053d0b5-180c-44f3-8f2b-da0447e60f15)

**Comment by tutugreen** [comment]
Sorry for re-replying to this issue, mainly because I just saw that the http email provider also update, and I see a several codes that are very similar.

The insights given by AI point out that the PostForm usage may be incorrect, so this may also have an effect on newly submitted HTTP Email providers @link89 (#2542) as well.

https://github.com/casbin/casdoor/blob/374928e7190bc8022fc957a8d40c6056837db1e1/email/http.go#L46

![2023-12-14-Email-1](https://github.com/casbin/casdoor/assets/7879628/afa86cb9-7097-48dc-922e-97291e149d96)

![2023-12-14-Email-2](https://github.com/casbin/casdoor/assets/7879628/41c732d3-2f8d-4009-8707-9f52ee592cbe)

![2023-12-14-1](https://github.com/casbin/casdoor/assets/7879628/be60e796-eba4-4266-80ca-5ff321420002)

![2023-12-14-2](https://github.com/casbin/casdoor/assets/7879628/a6e99ae4-fe93-4772-960f-906a8bd8d5ba)

Found `PostForm` in golang document can be used in `http.Client` or `http.Response` (as Server) but not `http.Request` (as Client), so maybe AI is right? 

(kind of busy right right now, not very familiar with golang and still tossing around the compilation/network environment, will try again if I can be of any help over the weekend)

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casdoor/commit/be637fca8150e04c7475da6c811644efc3ab86fd
