### ISSUE TITLE
[feature request] Email and SMS provider should support webhook type

### ISSUE THREAD

**Issue by link89** [casbin/casdoor#2536]
Currently the Email provider only supports limited type. Whenever there are requirements for a new Email backend, it has to be implement in casdoor server and make a new release.

To address this issue, I think casdoor should make of use webhook mechanism when possible. A typical use case is to verify user's Email or SMS. It's common that users of casdoor have their own email/sms providers that may no supported by casdoor yet, or they want to implement their own rules before sending code to the target user. In this case, webhook will be a good option for a user to integrate their system with casdoor. 

By implement the webhook mechanism, all it needs is to allow users to set a webhook url, and casdoor will send all necessary context data to the url via a POST request, and then acts accordingly with the response.

Relative issues:
* https://github.com/casbin/casdoor/issues/2534.

**Comment by hsluoyz** [comment]
@link89 

For Email, you can choose `Default` type to support all different Email providers like: https://door.casdoor.com/providers/admin/provider_email_sendgrid

![image](https://github.com/casbin/casdoor/assets/3787410/3a6d5c72-e19a-4148-9193-9803da8731d5)


For SMS, you can choose `Custom HTTP` type to send webhook-like request

![image](https://github.com/casbin/casdoor/assets/3787410/331c0f9f-06e5-4df9-96dc-a180c1d5d268)

**Comment by link89** [comment]
@hsluoyz Default email type is just a smpt client.  Email should also have a Custom HTTP method llike SMS. In my case I want to block some email address to register account, without a webhook I guess I can only implement my filter rule in casdoor. And with Custom HTTP we can use a pool of email addresses to send email instead of just one to avoid rate limit of email provider.
