### ISSUE TITLE
TOTP without password

### ISSUE THREAD

**Issue by jadiaheno** [casbin/casdoor#2538]
Hi, is it possible to have this authentication flow:
1. User enters their phone number
2. OTP is sent via SMS
3. User enters the OTP
4. Success!

If it's not possible out of the box, can i create a policy for it?  Or the best would be to just fork the project and add it myself? Regards.

**Comment by hsluoyz** [comment]
@jadiaheno it's already supported, see demo site: https://door.casdoor.com/login

![image](https://github.com/casbin/casdoor/assets/3787410/f337fdb0-b792-43d9-8691-9a758df7070a)

**Comment by hsluoyz** [comment]
@jadiaheno improved by: https://github.com/casbin/casdoor/pull/2566
