### ISSUE TITLE
Add lark provider

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#254]
Refer to: https://github.com/casbin/casdoor/tree/master/idp

See docs: https://open.feishu.cn/document/home/index

Some useful code (maybe):

- https://github.com/edwardzhou/ueberauth_feishu/blob/master/lib/ueberauth/strategy/feishu/oauth.ex
- https://django-allauth.readthedocs.io/en/latest/overview.html

**Comment by sh1luo** [comment]
work on it.
