### ISSUE TITLE
[question] database structure migration

### ISSUE THREAD

**Issue by jump2cn** [casbin/casdoor#2540]
hi team,
I'm looking to upgrade the casdoor from v1.308.0 to v1.472.0 . the casdoor document says that xorm can help migrate the database structure, is it an automated process or do I need to add migrate code for all table changes?

in my experience, some orm migrate need coding every change of model, do we have any existing code file like that?

**Comment by hsluoyz** [comment]
@jump2cn XORM will auto-migrate
