### ISSUE TITLE
[Bug] slash in groups names prevents to delete or access them afterward

### ISSUE THREAD

**Issue by tsaquet** [casbin/casdoor#2544]
Hello, 

I am using the last version of casdoor docker image.

I was trying to build a group hierarchy from a go program, using the golang sdk.

I wanted to have two subgroups (children of different parent groups) to have the same name. That was forbidden.

I decided to use a "/" in the name to do something like that : 

- Parent group 1 : "p_grp_1"
- Parent group 2: "p_grp_2"
- Child1 : "p_grp_1/sub_grp"
- Child2 : "p_grp_2/sub_grp"

... It worked.

But then, I wanted to delete those groups to pursue my tests...

- Deletion (via SDK or via GUI) gives that error : `error(*encoding/json.SyntaxError) *{msg: "invalid character '<' looking for beginning of value", Offset: 2}`
- And I cannot display the groups through the GUI (Not found)

Short term solution : prevent the usage of "/" in the groups names
Long solution : allow two groups to have the same name when they are not in the same parent group ?

**Comment by hsluoyz** [comment]
@tsaquet "/" is a reserved keyword heavily used by Casdoor itself and should not be used in user or group names

**Comment by tsaquet** [comment]
> @tsaquet "/" is a reserved keyword heavily used by Casdoor itself and should not be used in user or group names

Yes, I understand and I agree, that is why it is a bug to accept it in group name. The API should answer bad request.
It is even more a bug since everything in broken in groups after that, I had to fix that manually in the db, that should not happen.

**Comment by tsaquet** [comment]
Addendum: I just tester, I can also use "/" from the web interface which is a bigger problem.
