### ISSUE TITLE
Hausura Error fetching JWK: ConnectionTimeout

### ISSUE THREAD

**Issue by zuohuadong** [casbin/casdoor#2551]
When I follow the documentation：
https://casdoor.org/zh/docs/integration/Haskell/Hasura/

### ERROR：
hasura-1   | Error fetching JWK: ConnectionTimeout
hasura-1 exited with code 0
hasura-1   | {"detail":{"info":{"admin_secret_set":true,"auth_hook":null,"auth_hook_mode":null,"conso                                                                                                   le_assets_dir":null,"console_sentry_dsn":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_rea                                                                                                   d_cookie":null},"enable_allowlist":false,"enable_console":true,"enable_maintenance_mode":false,"enable_meta                                                                                                   data_query_logging":false,"enable_telemetry":true,"enabled_apis":["config","pgdump","metadata","graphql"],"                                                                                                   enabled_log_types":["webhook-log","http-log","startup","query-log","websocket-log"],"events_fetch_batch_siz                                                                                                   e":100,"experimental_features":[],"graceful_shutdown_timeout":60,"infer_function_permissions":true,"jwt_sec                                                                                                   ret":[{"audience":null,"claims_map":{"x-hasura-allowed-roles":["user","editor"],"x-hasura-default-role":"us                                                                                                   er","x-hasura-user-id":"userID"},"header":null,"issuer":null,"jwk_url":"https://ds.izm.cool/.well-known/jwk                                                                                                   s"}],"live_query_options":{"batch_size":100,"refetch_delay":1},"log_level":"info","port":8080,"remote_schem                                                                                                   a_permissions":false,"server_host":"HostAny","stringify_numeric_types":false,"transaction_isolation":"ISOLA                                                                                                   TION LEVEL READ COMMITTED","unauth_role":"anonymous","use_prepared_statements":true,"v1-boolean-null-collap                                                                                                   se":false,"websocket_compression_options":"NoCompression","websocket_connection_init_timeout":"Refined (Sec                                                                                                   onds {seconds = 3s})","websocket_keep_alive":"KeepAliveDelay {unKeepAliveDelay = Refined (Seconds {seconds                                                                                                    = 5s})}"},"kind":"server_configuration"},"level":"info","timestamp":"2023-12-18T16:33:48.044+0000","type":"                                                                                                   startup"}

![image](https://github.com/casbin/casdoor/assets/11203929/f011b00d-5399-4632-bfae-4a5cf53435c0)

Should I add encryption? Can you provide any documentation?

**Comment by hsluoyz** [comment]
@zuohuadong it seems that your error is `x509: malformed serial number`: https://ds.izm.cool/.well-known/jwks

![image](https://github.com/casbin/casdoor/assets/3787410/e215dad6-9e76-462b-b870-0bfc55dd23a7)

Don't upload some wired, bad-format certs to Casdoor. Use Casdoor-generated certs if you are not familiar with it.

Here's an example of good certs: https://door.casdoor.com/.well-known/jwks

![image](https://github.com/casbin/casdoor/assets/3787410/f07d8694-182e-4f10-a223-87f02f40bf29)
