### ISSUE TITLE
Can the built-in LDAP server support the LDAPS protocol

### ISSUE THREAD

**Issue by igangang** [casbin/casdoor#2555]
The current LDAP server only supports LDAP protocol connections, which pose security concerns. Can we consider supporting LDAPS?

**Comment by hsluoyz** [comment]
@igangang Casdoor itself doesn't serve SSL certificates. You need to have something like Nginx as reverse proxy to server HTTPs  from HTTP. It's similar to LDAPS and LDAP. For now, Casdoor itself won't handle such thing.

The Nginx config to serve LDAPS from Casdoor LDAP is:

```nginx
stream {
    upstream ldap_backend {
        server 127.0.0.1:389;  # Port where Casdoor LDAP server is running
    }

    server {
        listen 636 ssl;  # LDAPS port
        ssl_certificate /path/to/your/cert.pem;  # SSL certificate
        ssl_certificate_key /path/to/your/key.pem;  # SSL private key

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        proxy_pass ldap_backend;
    }
}
```
