### ISSUE TITLE
The mfa verification page failed to render, without a QR code or verification code input box

### ISSUE THREAD

**Issue by lucklyt** [casbin/casdoor#2557]
![image](https://github.com/casbin/casdoor/assets/150762476/228099b3-ff29-4c42-9a10-834d8ed08059)

**Comment by leo220yuyaodog** [comment]
@lucklyt Can you provide steps how to reproduce it and mfa related setting?

**Comment by lucklyt** [comment]
I just start casdoor on my local machine, and login my account, not admin. Click on My Account in the upper right corner to enter the user editing page, then click setup button ,both sms ,app, email tried. after verify password it came to the verify code   page screened I post, but nothing showed. the api return success and has the expected init data, but not rendered.
I know very little about Front-end, is the prompt in the screenshot incorrect?
![image](https://github.com/casbin/casdoor/assets/150762476/a326a080-3178-4087-acde-90e1f1b316d2)
![image](https://github.com/casbin/casdoor/assets/150762476/c98ba71f-54c0-43a9-b43b-6767e75b3253)

**Comment by lucklyt** [comment]
before I login in, I run make frontend first, then I run make run to start the server

**Comment by hsluoyz** [comment]
@lucklyt reproduce your issue in the modifiable demo site: https://demo.casdoor.com/

**Comment by lucklyt** [comment]
@hsluoyz cannot reproduce in the demo, and my local environment return to normal,  it's really strange...
