### ISSUE TITLE
Can't Link user to custom OAuth provider

### ISSUE THREAD

**Issue by EriTang** [casbin/casdoor#2564]
<img width="743" alt="1703946792006" src="https://github.com/casbin/casdoor/assets/73655702/ce3b790a-16c2-4d43-87c7-60378f8746a5">
I have add 3rd-party providers and ssign to organization
but user in account page can't find bottom to link 3ray-party providers

**Comment by hsluoyz** [comment]
The user's `signupApplication` should be configured. Make sure the correct application
