### ISSUE TITLE
What if I forgot recovery code of MFA?

### ISSUE THREAD

**Issue by Tristan0430** [casbin/casdoor#2565]
Like the title, how can I reset MFA by CLI?

**Comment by hsluoyz** [comment]
@Tristan0430 Casdoor has no CLI. For your case, you can either:

1. Use `built-in/admin` admin account to change Casdoor setting
2. Use app's clientId/secret to call Casdoor HTTP API to change setting
3. Manually change Casdoor DB to change setting
