### ISSUE TITLE
Provide linux/arm64 Docker images again

### ISSUE THREAD

**Issue by knusperkrone** [casbin/casdoor#2567]
The last Docker image that supported `linux/arm64 ` is [v1.428.0](https://hub.docker.com/layers/casbin/casdoor/v1.428.0/images/sha256-bc472f415603a21713d3ac577970976d14627c94621134446c0f6c7b6087de99?context=explore), then the support was dropped

It would be very nice to still support this arch, as I've mostly chosen casdoor in favor of other applications, as it does have a low ressource profile and therefore can self-hosting on an arm based (home-)servers

**Comment by hsluoyz** [comment]
Dup with: https://github.com/casbin/casdoor/issues/2416

**Comment by hsluoyz** [comment]
Thanks to this PR: https://github.com/casdoor/casdoor/pull/2969 , the arm64 image is back starting from v1.621.0: https://hub.docker.com/r/casbin/casdoor/tags
