### ISSUE TITLE
Why do I get error: OIDC callback failed: Error: OIDCConfig: email not verified for xxxx?

### ISSUE THREAD

**Issue by Tristan0430** [casbin/casdoor#2568]
After I have set email provider successfully when I integrate OIDC into Grist Table app, Grist always says Casdoor doesn't claim `emailVerified` as `True`. How to solve this?

**Comment by hsluoyz** [comment]
@Tristan0430 fixed by: https://github.com/casbin/casdoor/commit/00efdf1d03f189e42e76962363d5688148d6af4d
