### ISSUE TITLE
After logout, casdoor returns error...

### ISSUE THREAD

**Issue by Tristan0430** [casbin/casdoor#2569]
{
  "status": "error",
  "msg": "miss param: id_token_hint",
  "sub": "",
  "name": "",
  "data": null,
  "data2": null
}

**Comment by hsluoyz** [comment]
@Tristan0430 see OIDC logout: https://openid.net/specs/openid-connect-rpinitiated-1_0.html

**Comment by StringKe** [comment]
@hsluoyz 建议 id_token_hint 不强制要求，或者有参数来设置是否需要在登出的时候强制验证 id_token_hint
