### ISSUE TITLE
LDAP non-standard response on anonymous bind request

### ISSUE THREAD

**Issue by ttimasdf** [casbin/casdoor#2572]
I'm not an expert on LDAP protocol and this issue is totally based on inspections in Wireshark. This misbehaviour is treated as a fatal error when binding casdoor LDAP server to a Synology DSM 7.2 system.

An anonymous bind request looks like this in Wireshark

```
Lightweight Directory Access Protocol
    LDAPMessage bindRequest(1) "<ROOT>" simple
        messageID: 1
        protocolOp: bindRequest (0)
            bindRequest
                version: 3
                name: 
                authentication: simple (0)
                    simple: 
        [Response In: 28]
```

The Synology LDAP Server suite (which is an OpenLDAP server) returns the following

```
Lightweight Directory Access Protocol
    LDAPMessage bindResponse(1) inappropriateAuthentication (anonymous bind disallowed)
        messageID: 1
        protocolOp: bindResponse (1)
            bindResponse
                resultCode: inappropriateAuthentication (48)
                matchedDN: 
                errorMessage: anonymous bind disallowed
        [Response To: 502]
        [Time: 0.000182000 seconds]
```

Casdoor LDAP server returns with this error

```
Lightweight Directory Access Protocol
    LDAPMessage bindResponse(1) invalidDNSyntax (getNameAndOrgFromDN() error: please use Admin Name format like cn=xxx,ou=xxx,dc=example,dc=com)
        messageID: 1
        protocolOp: bindResponse (1)
            bindResponse
                resultCode: invalidDNSyntax (34)
                matchedDN: 
                errorMessage: getNameAndOrgFromDN() error: please use Admin Name format like cn=xxx,ou=xxx,dc=example,dc=com
        [Response To: 26]
        [Time: 0.000768000 seconds]
```

**Comment by hsluoyz** [comment]
@leo220yuyaodog any idea about this?

**Comment by leo220yuyaodog** [comment]
> @leo220yuyaodog any idea about this?

Maybe we can improve corresponding error handling for this situation, which is currently rough for LDAP connections.

**Comment by ttimasdf** [comment]
I largely refactored the existing codebase of LDAP component to resemble 80% of an OpenLDAP server on #2574. Further works need to be done to make Samba authentication work (store NTLM hash somewhere in casdoor). At least now it is functional, works perfectly as an LDAP provider for my NAS. 😉

![image](https://github.com/casbin/casdoor/assets/2762704/fab9821d-404f-4233-9c09-8a1eca918871)

**Comment by hsluoyz** [comment]
Reverted by: https://github.com/casbin/casdoor/pull/2611

**Comment by tianyanli** [comment]
@ttimasdf Do you have any follow-up plans regarding the addition of Synology NAS to Casdoor LDAP Server? I encountered the same problem.
