### ISSUE TITLE
upgrade go to 1.20

### ISSUE THREAD

**Issue by sp71** [casbin/casdoor#2573]
Currently casdoor uses go 1.16 which is no longer a supported [release](https://go.dev/doc/devel/release). We can upgrade to the latest 1.20 version. Need to update go.mod && .github/workflows/build.yml

> Release Policy
Each major Go release is supported until there are two newer major releases

**Comment by hsluoyz** [comment]
Go 1.20 is supported. No need to change version here.

**Comment by sp71** [comment]
I see the disconnect. The [Dockerfile](https://github.com/casbin/casdoor/blob/master/Dockerfile#L7C2-L7C2) uses 1.20 but the project itself lists 1.16 in the [go.mod](https://github.com/casbin/casdoor/blob/master/go.mod#L3).

**Comment by hsluoyz** [comment]
Keeping compatibility for old version is good. Won't update if there's no any benefits
