### ISSUE TITLE
hasura  jwt error 

### ISSUE THREAD

**Issue by zuohuadong** [casbin/casdoor#2575]
```
HASURA_GRAPHQL_JWT_SECRET: '{"claims_map": {
      "x-hasura-allowed-roles": ["user","editor"],
      "x-hasura-default-role": "user",
      "x-hasura-user-id": "userID"
    },"jwk_url":"<Casdoor endpoint>/.well-known/jwks"}'
```

The roles given in the documentation are fixed.

Are there any relevant cases?
like:

```
      "x-hasura-allowed-roles": { "path": "$..roles[*].name" },
      "x-hasura-default-role": { "path": "$.roles[0].name" },
      "x-hasura-user-id": { "path": "$.id" }
      },"jwk_url":"<Casdoor endpoint>/.well-known/jwks"}'
```
but:

![企业微信截图_17043827778010](https://github.com/casbin/casdoor/assets/11203929/f5f76754-e253-41c0-a5d8-4f11042570ac)

**Comment by hsluoyz** [comment]
@zuohuadong why you need to set it to be dynamic?

**Comment by zuohuadong** [comment]
@hsluoyz 

Because of actual use, you need to add a role to casdoor.

**Comment by hsluoyz** [comment]
@zuohuadong I have improved your version to the following, because Casdoor user's roles is a string array. So can you try it?

```
      "x-hasura-allowed-roles": { "path": "$.roles" },
      "x-hasura-default-role": { "path": "$.roles[0]" },
      "x-hasura-user-id": { "path": "$.id" }
      },"jwk_url":"<Casdoor endpoint>/.well-known/jwks"}'
```

**Comment by hsluoyz** [comment]
Closed as resolved

**Comment by AlexanderChen1989** [comment]
> [@zuohuadong](https://github.com/zuohuadong) I have improved your version to the following, because Casdoor user's roles is a string array. So can you try it?
> 
> ```
>       "x-hasura-allowed-roles": { "path": "$.roles" },
>       "x-hasura-default-role": { "path": "$.roles[0]" },
>       "x-hasura-user-id": { "path": "$.id" }
>       },"jwk_url":"<Casdoor endpoint>/.well-known/jwks"}'
> ```

 Casdoor user's roles is not  string array. !!!!!!!
