### ISSUE TITLE
Support custom path to configuration file

### ISSUE THREAD

**Issue by vaminakov** [casbin/casdoor#2580]
It is possible to store frontend almost everywhere with frontendBaseDir config parameter. But it's impossible to store somewhere config file, besause it hardcoded in ormer.go.
It'll be fine to make configuration file as parameter to binary file, like ./casdoor --conf /etc/casdoor.conf

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casdoor/commit/2d6fae32bea309387733a938649ee8e0cee70993
