### ISSUE TITLE
Getting "JSON.parse: unexpected character at line 1 column 1 of the JSON data" when starting the frontend project

### ISSUE THREAD

**Issue by LaurenceYoungDev** [casbin/casdoor#2588]
I'm getting a `JSON.parse error` when starting the frontend project, I'm using `Node@18.19.0` with `Yarn@1.22.21`, and I haven't touched anything after cloned the project.
![Snipaste_2024-01-08_10-35-43](https://github.com/casbin/casdoor/assets/20877320/35b91d86-d358-41e2-8069-e829b16971d3)

**Comment by hsluoyz** [comment]
@LaurenceYoungDev every CI process is passing. This is your own env's problem.
