### ISSUE TITLE
question: email domain validation for registration

### ISSUE THREAD

**Issue by xgenvn** [casbin/casdoor#2595]
Hi,

I need to add the constraint to limit the email domains that can be registered, or some rules from the user preference after OAuth consent. 
In the case of OAuth2, some providers such as Google provided support for domain limitation. But if we turn off registration, OAuth2 step cannot pass. If we open the registration feature, we cannot limit the domain that can register via email or phone number (or I don't know this feature available yet).
There are several workarounds I have been thinking of:
1. Add invitation code, keep current UI, so that only people with invitation code can register via inputted email.
2. For better UI and UX, add invitation code, rebuild interface to login without register with email (or CSS custom to hide the form). Only show the login with SSO.

More comprehensively, I want to know if there is a roadmap or plan to support dynamic rules at multiple hooks. Similar to pocketbase.io that using goja as JS engine for extending at runtime. I will love to contribute on this part.

Thanks.

**Comment by hsluoyz** [comment]
@xgenvn please don't brainstorm here, this is not the right place. Please exactly describe the feature request here (it should be one concrete, detailed feature)

**Comment by xgenvn** [comment]
你可以给个指引那个地方是用于讨论的？你也可以直爽地说这些都需要通过企业渠道。如果你要英文阅读问题的话我也可以用中文。你不能直接关掉issue然后说不是对地方啊？在Discord问就说到GitHub开个issue，来这边详细地问问就说不是地方。我就不懂你们怎么管理项目，QQ吗？还是微信的，直接说就行。
我不是描述很详细上面了？另外，我是在寻大家想法来改善这项目，有啥错了你？
