### ISSUE TITLE
The user: xxx doesn't exist error when calling Casbin API

### ISSUE THREAD

**Issue by wangyuefan09** [casbin/casdoor#2602]
When using the built-in Casbin in Casdoor, the interface for obtaining all roles through the open Casbin API returned the following: 'status': 'error', 'message': 'The user: app/app-built-in doesn't exist.'

**Comment by hsluoyz** [comment]
@wangyuefan09 fixed by: https://github.com/casbin/casdoor/commit/177f2f2f11f04a16209df78bb32d5edf6747c055

Now you can use the GET parameter like: `/api/get-all-objects?userId=built-in/admin` to specify the user that want to retrieve the roles

**Comment by wangyuefan09** [comment]
我目前不明确是不是我配置的问题，现在请求依然是'The user: app/app-built-in does'不存在，即使用了您新提供的接口
