### ISSUE TITLE
LDAP missing attributes 

### ISSUE THREAD

**Issue by NhProGamer** [casbin/casdoor#2608]
There is a problem with LDAP search, we can only access to basic attributes:
![image](https://github.com/casbin/casdoor/assets/44909803/9540e739-45ea-4e3e-a222-e1e9724f0f03)
For example for my email server i need more attrubites like quota, aliases, email etc...
(edit: i just realised my password is on he screen lmao. I have changed that.)

**Comment by hsluoyz** [comment]
@NhProGamer 

1. What did you do?
2. What do you expect?
3. What you got instead?

**Comment by hsluoyz** [comment]
@NhProGamer the LDAP part has recently been fixed. Can you test the latest v1.502.0 version to see if it's fixed? https://github.com/casbin/casdoor/releases/tag/v1.502.0

**Comment by NhProGamer** [comment]
after the update there are other attributes, but can you add all attributes from an organisation like email, gender, number phone, display name, avatar, etc... same logic for all added attributes
![image](https://github.com/casbin/casdoor/assets/44909803/dc10c818-6c7a-4eb4-a7b6-13e0e99cddf0)

**Comment by hsluoyz** [comment]
@NhProGamer can you point out where to add the code? Or can you make a PR?

**Comment by NhProGamer** [comment]
nevermind, i just realised we can access to all of that data just by defautlt with ldapsearch it not shows all like the user's password etc...
