### ISSUE TITLE
The built-in ldap server cannot find users through the cn attribute

### ISSUE THREAD

**Issue by igangang** [casbin/casdoor#2610]
Starting from version 1.489.0, using the built-in ldap server and using the cn attribute to search for users cannot be found.
```
2024/01/12 01:02:12 Connection client [3] from 172.18.0.7:47272 accepted
2024/01/12 01:02:12 <<< 3 - BindRequest
2024/01/12 01:02:12 >>> 3 - BindResponse
2024/01/12 01:02:12 <<< 3 - SearchRequest
2024/01/12 01:02:12 ******************************
2024/01/12 01:02:12 **** ROUTE MATCH ;  SEARCH****
2024/01/12 01:02:12 ******************************
2024/01/12 01:02:12 >>> 3 - SearchResultDone
2024/01/12 01:02:12 Unmatched search request. filter=(&(cn=xiaoxiao))
2024/01/12 01:02:12 Error readMessagePacket: EOF
```

**Comment by hsluoyz** [comment]
@ttimasdf we checked that this issue is caused by your PR: https://github.com/casbin/casdoor/pull/2574 as your PR has trigged the 1.489.0 release.

![image](https://github.com/casbin/casdoor/assets/3787410/647cf311-9797-4e55-8572-2b421165dbd0)


Can you fix it?

**Comment by ttimasdf** [comment]
sure, i'll check it out this week

**Comment by hsluoyz** [comment]
@ttimasdf we have multiple sources to report issues about this part of code. The PR: https://github.com/casbin/casdoor/pull/2574 will be reverted shortly to provide them a quick fix.

As a advice, if you still want to fix the Synology related issue, make a small PR next time and don't do large-scale refactoring, given the code quality cannot be fully guaranteed.

**Comment by ttimasdf** [comment]
Reverting this PR is okay but there could be a discussion among you maintainers regarding what's the functionality of the LDAP server module should be. As for now, any additional functionality on this module would need a PR of >= the size of #2574 as the current implementation contains too much hardcoded elements.

We can also change the "default" code branch (the "Unmatched search request" error) to replicate the behaviour before my PR, which would also resolve this issue.

**Comment by hsluoyz** [comment]
@ttimasdf I'm OK with changes even aggressive ones. The key here is that PR's quality needs to reach the bar so that there won't be a lot of issues complaining that the PR has brought them new bugs. Or the PR owner should be very responsive to fix the issues in short time. Because when people use the project, they blame the whole project. I know PR author wants to get their PR merged and get their own scenario done but sometimes they care not that much about how other people encounter bugs. This is why maintainers exist and make decisions to keep most people happy.

**Comment by hsluoyz** [comment]
Another case (maybe) fixed by this issue: https://github.com/casbin/casdoor/issues/2608

**Comment by ttimasdf** [comment]
> when people use the project, they blame the whole project.
> This is why maintainers exist and make decisions to keep most people happy.

You are right, and I'm willing to help resolving issues if my code breaks someone else's running server. 🫣

**Comment by muwubbq** [comment]
Is this issue still unresolved in 2025?

**Comment by hsluoyz** [comment]
@muwubbq create new issue, this one is too old
