### ISSUE TITLE
  Invalid spec: Could not convert Swagger 'Casdoor RESTful API' to OpenAPI Specification. Could not resolve reference #/definitions/jose.JSONWebKey

### ISSUE THREAD

**Issue by zuohuadong** [casbin/casdoor#2618]
in 1.476.0：  
![image](https://github.com/casbin/casdoor/assets/11203929/7043946e-b0b1-4fc5-ba11-66646332ffd6)

![image](https://github.com/casbin/casdoor/assets/11203929/1fe9c16f-fa47-4e68-8d94-925445fc39d3)

in 1.492.0: error：

![image](https://github.com/casbin/casdoor/assets/11203929/119f0304-23bc-40ea-b3df-4ce98cbb5940)

![image](https://github.com/casbin/casdoor/assets/11203929/b95f00e0-95f6-46cb-a228-3fdab86ffac6)

**Comment by hsluoyz** [comment]
@zuohuadong use latest version to test

**Comment by hsluoyz** [comment]
@zuohuadong what is the software/website/platform in the screenshot?

![image](https://github.com/casbin/casdoor/assets/3787410/959a12f6-d04f-4916-903d-ae7db2457fb4)

**Comment by zuohuadong** [comment]
@hsluoyz  Thanks, it has been solved in the latest version.
