### ISSUE TITLE
OIDC with wikijs report "invalid email / username or password"

### ISSUE THREAD

**Issue by sunyajie0829** [casbin/casdoor#2619]
I added the OIDC of Casdoor using the authenticator on Wikijs, and the email claim field was filled in as 'email'

When I log in with the username or email in casdoor, it prompts Invalid email/username or password. How do I adjust it

**Comment by hsluoyz** [comment]
@sunyajie0829 is password correct? You can check the "User" table in Casdoor DB

**Comment by sunyajie0829** [comment]
yeah,the password is wrong.
but after i set correct password,after redirect,wikijs says 'oops,something went wrong,you are not authorized to login'

**Comment by hsluoyz** [comment]
@sunyajie0829 can you try to connect wikijs with other SSO solutions like Keycloak or Okta or Auth0?

**Comment by sunyajie0829** [comment]
close

**Comment by hsluoyz** [comment]
@sunyajie0829 why close?
