### ISSUE TITLE
Remove Payment Integration

### ISSUE THREAD

**Issue by istiak101** [casbin/casdoor#2620]
I have previously tried Casdoor and forked to remove the payment integration entirely.

I don't know why an IDP should have a payment integration with products. It smells and with so many things there is a greater chance of this being hacked.

I tried Keycloak, Ory(Kratos,Hydra) and Casdoor. I needed an UI and Keycloak was heavy with much RAM(because it's Java) but it's a fantastic product and I am thinking about porting this with same model. Ory Kratos is API first but I think I can develop a frontend for it. My last resort is to build my own boat.

I want to give Casdoor a second chance but from my forking experience I can say I can easily break backend just by sending garbage data/modifying the UI. No validation of data whatsoever. And the code quality seems not so great.

Also why would a IDP load JS/CSS from GitHub? And previously you had a Baidu tracker.

So I think you can work on improving these before comparing this with Keycloak on Hacker News.

**Comment by hsluoyz** [comment]
@istiak101 

1. From our roadmap, Casdoor is not only an IAM, but also a SaaS management platform. So it integrates with some payment providers just like OAuth providers. If you don't use it, you can just ignore it or comment related code (it's OSS).
2. If some APIs fail to validate data, you can provide examples?
3. We choose not to put all static resources in the code repo.

**Comment by istiak101** [comment]
Thanks, I have no plan to fork it. There are underlying libraries maintained by you(e.g casbin). Also I am not confident with the code quality. Also if there is no chance of my changes being merged upstream I don't want to go back and forth merging your changes on my fork. My best resort seems at this point Ory Network and then maybe porting Keycloak after some time.
