### ISSUE TITLE
feat: Hide passwords in syncer

### ISSUE THREAD

**Issue by leoncamel** [casbin/casdoor#2622]
Showing the password as plaintext is not a good idea, please consider hide the password.

![image](https://github.com/casbin/casdoor/assets/218590/4b596e30-5f3f-423d-8e66-a4a4530ce7e4)

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casdoor/commit/b8db07db4d601bba809054041e0950a310b4de96
