### ISSUE TITLE
bug: A non-admin user edits their account information and clicks "Save & Exit", and then they are redirected to /users.

### ISSUE THREAD

**Issue by zzzz0317** [casbin/casdoor#2630]
A non-admin user edits their account information and clicks "Save & Exit", and then they are redirected to /users.

Due to insufficient permissions, the interface will freeze. I believe it should be redirected to /apps or /.

![image](https://github.com/casbin/casdoor/assets/16097046/39514409-46c7-45f5-93b5-5de76b79787d)

**Comment by hsluoyz** [comment]
@zzzz0317 fixed by: https://github.com/casbin/casdoor/commit/f4c873ffe6bf9e212264c8d8d59953cd6a2c81ec
