### ISSUE TITLE
bug: user not in built-in organization can not setup mfa

### ISSUE THREAD

**Issue by zzzz0317** [casbin/casdoor#2631]
I create a new organization, and unable to set up MFA by myself. I can only set up SMS and email types of MFA on the administrator page. The APP type requires scanning a QR code, which cannot be configured by the administrator. When users try to configure MFA on their own, none of the three types of MFA are displayed correctly on the frontend interface. However, by using the Network tab in F12, it is possible to see that the API is functioning properly.

![image](https://github.com/casbin/casdoor/assets/16097046/fd9e11ce-d766-4a46-add8-d5c7afbcbb59)

**Comment by leo220yuyaodog** [comment]
@zzzz0317  I follow your steps create a new organization and a user.  The use can setup MFA itself.  I'm not sure what casues the bug you showed,  you can see the video to check it.

https://github.com/casbin/casdoor/assets/71440988/9609f496-c05a-43cb-81de-f63209ba0489

**Comment by zzzz0317** [comment]
![image](https://github.com/casbin/casdoor/assets/16097046/d8c46b25-011a-4756-b5f4-4d9512854b6d)
![image](https://github.com/casbin/casdoor/assets/16097046/9467b8cb-f13a-4419-8e00-d9544e2c38e6)

I found that this value is empty, and after I assigned an app to this account, the problem was solved.
I don't know why this value is empty. When I create an empty account, it uses "app-built-in" as the default app, but "app-built-in" does not belong to my new organization.

**Comment by zzzz0317** [comment]
![image](https://github.com/casbin/casdoor/assets/16097046/200cab2d-0ccf-4088-adcc-306850652083)
![image](https://github.com/casbin/casdoor/assets/16097046/c03d6f7c-78c2-4e57-bee4-3ec2561d751b)

And after I set up an MFA, the setup button is missing on my account page, but when I set up another MFA, the MFA method that has already been set up appears on the MFA setup page.

**Comment by hsluoyz** [comment]
@zzzz0317 can you provide demo video about "And after I set up an MFA, the setup button is missing on my account page, but when I set up another MFA, the MFA method that has already been set up appears on the MFA setup page." ?

**Comment by hsluoyz** [comment]
@zzzz0317 

> When I create an empty account, it uses "app-built-in" as the default app, but "app-built-in" does not belong to my new organization.

Fixed by: https://github.com/casbin/casdoor/commit/104f975a2ffdc2b31ea64fed2ce835a017a1c8a6

**Comment by leo220yuyaodog** [comment]
> And after I set up an MFA, the setup button is missing on my account page, but when I set up another MFA, the MFA method that has already been set up appears on the MFA setup page.

It seems that you are confused by how the UI behaves differently in these two places. In fact, I expected to be able to override the previous configuration after setting it, but it didn't show up in the user page.  I will fix it by add an `edit` button in the user page.
