### ISSUE TITLE
The get user interface returned data that does not conform to the swagger specification.

### ISSUE THREAD

**Issue by zuohuadong** [casbin/casdoor#2634]
![mmexport1705742407588](https://github.com/casbin/casdoor/assets/11203929/6d7a1236-66be-4643-a0f6-fec86118e0fd)

As shown in the figure, get-user the interface returns data in html format instead of standard json data, which is not Swagger-compliant and does not facilitate api usage it should look like this:

![mmexport1705742517810](https://github.com/casbin/casdoor/assets/11203929/2626dbfa-fbea-40f4-a5c1-c83f895d855a)

**Comment by hsluoyz** [comment]
@zuohuadong it's because you lacked `name` parameter besides `owner`, which triggered the backend panic. Beego crashes will render HTML. This is why you see HTML instead of JSON. Removing backend panic usage is in the plan, but not very soon to be done

**Comment by zuohuadong** [comment]
@hsluoyz Even if the argument is missing, it should return a JSON error instead of HTML, which will cause the downstream to not catch the error. It's not a good habit

**Comment by hsluoyz** [comment]
@zuohuadong can you give an URL from: https://github.com/beego/beego/tree/v1.12.12 ?

https://pkg.go.dev/github.com/dlt/beego/middleware is not official link
