### ISSUE TITLE
frontend: sms verification passcode field could not autocomplete on IOS web

### ISSUE THREAD

**Issue by SharplyQ** [casbin/casdoor#2638]
sms verification passcode field could not autocomplete on IOS web page
I have checked verification passcode field and find there is no "autocomplete=one-time-code" attribute.
This leads to no autofill sms code for ios user which is inconvenience.
Could we add "autocomplete=one-time-code" to sms verification code field?

<img width="921" alt="image" src="https://github.com/casbin/casdoor/assets/156662002/40bd9649-82fa-4201-877f-5902b63aa3cc">

**Comment by hsluoyz** [comment]
@SharplyQ sounds good. Can you make a PR to add it?
