### ISSUE TITLE
Unable to import roles with init_data

### ISSUE THREAD

**Issue by Sheryorov** [casbin/casdoor#2640]
I have an init_data.json file 
with fields: 
```
`
 "users": {
  ...  
     "name": "user1",
      "owner": "foo",
      "roles": [{"name": "role1"}]

 },
"roles:[{
      "owner": "foo", 
      "name": "role1"
}]
```
`
But UI doesn't show role for user1

**Comment by hsluoyz** [comment]
@Sheryorov use this template: https://github.com/casbin/casdoor/blob/master/init_data.json.template

**Comment by hsluoyz** [comment]
@Sheryorov any update on PR?

**Comment by Sheryorov** [comment]
I used this template and it work. Thanks
