### ISSUE TITLE
bug: SAML BINGING HTTP POST login error,response "unexpected EOF"

### ISSUE THREAD

**Issue by mahuihuang** [casbin/casdoor#2643]
use aliyun cloudsso as saml SP。SAML SP redirect use post method, SAMLRequest and RelayState repose in form data，frontend did't send `SAMLRequest` and `RelayState` on request payload.

## SP redirect response
![image](https://github.com/casbin/casdoor/assets/33620944/fd737d6d-04e4-4c35-84d7-fc5b90fce739)

![image](https://github.com/casbin/casdoor/assets/33620944/75dc191a-a9c8-459f-9cdd-da1fc67830c0)

## login  request payload
```bash
curl 'http://localhost:8000/api/login' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh;q=0.9,en;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: text/plain;charset=UTF-8' \
  -H 'Cookie: Hm_lvt_14752563c89f0870e93d2f6ac497f815=1704182104; ajs_anonymous_id=9eb0160f-6222-43ee-8db1-225bd487b329; _gcl_au=1.1.1282421203.1705393081; ajs_user_id=e9a26e61-9030-464e-a7c3-73b485fbc009; access-token=eyJhbGciOiJIUzI1NiIsImtpZCI6InYxIiwidHlwIjoiSldUIn0.eyJuYW1lIjoiQWRtaW4iLCJpc3MiOiJieXRlYmFzZSIsInN1YiI6IjEwMSIsImF1ZCI6WyJiYi51c2VyLmFjY2Vzcy5wcm9kIl0sImV4cCI6MTcwNjQ5NzUxNSwiaWF0IjoxNzA1ODkyNzE1fQ.g54hd_VxScDz1lcjrOos95PzoxG9XPJAro3JPRXexrY; user=101; casdoor_session_id=e051821a02ad224423d23e57a6f8598e' \
  -H 'Origin: http://localhost:8000' \
  -H 'Referer: http://localhost:8000/login/saml/authorize/admin/cloudsso' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  --data-raw '{"application":"cloudsso","organization":"built-in","username":"admin","password":"123","autoSignin":true,"signinMethod":"Password","type":"saml"}' \
  --compressed
```
![image](https://github.com/casbin/casdoor/assets/33620944/65df4a0f-1547-423e-8cae-d04e758a05eb)

## aliyun cloudsso setting
- ACS URL: https://signin-cn-shanghai.alibabacloudsso.com/saml/acs/xxxxxxx
- Entity ID: https://signin-cn-shanghai.alibabacloudsso.com/saml/sp/xxxxxx

## casdoor appliction setting
- redirect urls:  https://signin-cn-shanghai.alibabacloudsso.com/saml/sp/xxxxxx
- SAML response URL:  https://signin-cn-shanghai.alibabacloudsso.com/saml/acs/xxxxxxx

## refrence
[管理单点登录](https://help.aliyun.com/zh/cloudsso/user-guide/configure-sso?spm=a2c4g.11186623.0.0.2e296c69jLWh9R)
[Appgate (POST)](https://casdoor.org/docs/how-to-connect/saml/appgate)

**Comment by mahuihuang** [comment]
backend did't handle  SP  `/login/saml/authorize/:owner/:applicationName`  ,https://github.com/crewjam/saml/blob/main/identity_provider.go#L373

**Comment by hsluoyz** [comment]
@mahuihuang can you make a PR to fix it?

**Comment by hsluoyz** [comment]
@mahuihuang can you try this PR? https://github.com/casbin/casdoor/pull/2661

**Comment by tiny-v** [comment]
hi,

the casdoor version in my local is v1.651.0

i'm using Azure as the SP， Casdoor as the IDP, and i already enable the Saml Post Binding, but still get the "Unexpected EOF" error when login.
