### ISSUE TITLE
when we use token and application to query token, Is there a performance issue here 

### ISSUE THREAD

**Issue by allmelgr** [casbin/casdoor#2644]
object/token.go GetTokenByTokenAndApplication

here is the code reference
 #https://github.com/casbin/casdoor/blob/dd51bbbabfa79198a4ff7014c868cb2f6d863a5c/object/token.go#L46-L66

 #https://github.com/casbin/casdoor/blob/dd51bbbabfa79198a4ff7014c868cb2f6d863a5c/object/token.go#L286-L298

access_token and refresh_token are mediumtext
when the data growth, queries will be slow?

**Comment by hsluoyz** [comment]
@allmelgr can you make a PR to fix it?

**Comment by allmelgr** [comment]
> @allmelgr can you make a PR to fix it?


``` go
AccessTokenHash  string `xorm:"varchar(100) index" json:"accessTokenHash"` 
RefreshTokenHash string `xorm:"varchar(100) index" json:"refreshTokenHash"`
```
maybe use hash do pre filter is a way to improve the performance，if the hash algorithm is

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casdoor/commit/540f22f8bd2dbbabf7b7f64cbeba2a921e9d9c72
