### ISSUE TITLE
Support use organization's default avatar when creating user in web

### ISSUE THREAD

**Issue by dacongda** [casbin/casdoor#2646]
When creating a new user in web, i think it will be better to use organization's default avatar 
![image](https://github.com/casbin/casdoor/assets/47297289/41f4d928-2f3c-46dd-89b3-050327630a9a)
![image](https://github.com/casbin/casdoor/assets/47297289/8f817abc-b291-45c0-a09e-26d9c9c062af)

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casdoor/commit/71bb40055982f6ca4b3336fec1716ea82b60cfd3
