### ISSUE TITLE
[Help] Couldn't login to the super admin account

### ISSUE THREAD

**Issue by gitiy1** [casbin/casdoor#2650]
I have used casdoor for a while and I have created another organization on it, and when accessing the sso website, it would have a select opinion. Today i updated it to the latest version. However, when i tried to login to the super admin user in the built-in org, i select the built-in org and it showed the message "To access [xxx](https://sso.example.com/login/built-in?orgChoiceMode=None)(the name of my another org)". I clicked the [xxx](https://sso.example.com/login/built-in?orgChoiceMode=None) link and it would entered this page again. Now i coulnd't access the built-in organization and could only login to another organization. What could i do to regain access to the superadmin? Please help me!

**Comment by hsluoyz** [comment]
@gitiy1 hard to read your words and image what's happening, better with a video.

For org login, you can always login via: /login/<org-name> like: https://door.casdoor.com/login/casbin

**Comment by gitiy1** [comment]
https://github.com/casbin/casdoor/assets/91715524/d7f2d584-a587-4608-97ef-854bc98764ff

Sorry for troubling you. Here is the video.
It is so strange and i would like to find a way to regain access to the admin account. If there are amy guide about how to use curl or other tools and authorlize by api so that i could try to adjust the settings would also be helpful.

Thanks a lot for your help!
