### ISSUE TITLE
feat: add EmailVerifiedTime to user

### ISSUE THREAD

**Issue by sp71** [casbin/casdoor#2658]
Casdoor [users](https://github.com/casbin/casdoor/blob/master/object/user.go#L67) support EmailVerified and Email; however, it does not support a timestamp for when it was verified. Request is to add support for EmailVerifiedTime.

**Comment by hsluoyz** [comment]
@sp71 what's EmailVerifiedTime used for?

**Comment by hsluoyz** [comment]
It seems not very useful, closed here
