### ISSUE TITLE
bug: Sending incorrect application crashes casdoor

### ISSUE THREAD

**Issue by sp71** [casbin/casdoor#2668]
**Description**
When sending a post request to casdoor for `/api/signup`, casdoor crashes when the application field in the json is either empty or it's a value that does not belong to an application.

**Case 1: Empty Application Value**

1. signUp tries getting application [details](https://github.com/casbin/casdoor/blob/b7be1943fab81583daddb11942e175ebbf1e05bd/controllers/account.go#L91)
2. The [getApplication](https://github.com/casbin/casdoor/blob/ce0d45a70b164b70674deddbcc745cebb63a655d/object/application.go#L229) will return both empty values because the name is empty. 
3.  Signup proceeds to nil crash on [application](https://github.com/casbin/casdoor/blob/b7be1943fab81583daddb11942e175ebbf1e05bd/controllers/account.go#L97) variable since it's nil

**Case 2: Incorrect Application Value**
1. signUp tries getting application [details](https://github.com/casbin/casdoor/blob/b7be1943fab81583daddb11942e175ebbf1e05bd/controllers/account.go#L91)
2. The [getApplication](https://github.com/casbin/casdoor/blob/ce0d45a70b164b70674deddbcc745cebb63a655d/object/application.go#L256) will return both empty values because the application did not exist. 
3.  Signup proceeds to nil crash on [application](https://github.com/casbin/casdoor/blob/b7be1943fab81583daddb11942e175ebbf1e05bd/controllers/account.go#L97) variable since it's nil

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casdoor/commit/901867e8bb4b07284fc91f378b5641d5742a8b9c
