### ISSUE TITLE
Added support for user-defined login interfaces on mobile devices

### ISSUE THREAD

**Issue by strong-xiaoge** [casbin/casdoor#2670]
The customization of the login page is required if you intend to utilize third-party app authorization, such as WeChat, for logging into the mobile app. However, it is not possible to employ third-party authorization and one-click login via mobile number.

**Comment by hsluoyz** [comment]
@strong-xiaoge the English is bad and hard to understand. Can you stop using bad-quality LLM? Or use a good one like GPT-4 to translate your words?

**Comment by strong-xiaoge** [comment]
I have a mobile app. I want to use the WeChat app to authorize login. What do I need to do

**Comment by hsluoyz** [comment]
See: https://casdoor.org/docs/provider/oauth/Wechat
