### ISSUE TITLE
Issue with 2FA not working when LDAP authentication is enabled #2654

### ISSUE THREAD

**Issue by alexnet123** [casbin/casdoor#2675]
The issue was about a problem with two-factor authentication (2FA) not functioning correctly when LDAP authentication was enabled, identified by the issue number [#2654](tg://search_hashtag?hashtag=2654). Despite being reported, this issue remained unresolved, leading to the decision to open a new issue to address the ongoing problem.

**Comment by hsluoyz** [comment]
@alexnet123 can you provide a demo video to show this issue?

**Comment by alexnet123** [comment]
Thanks a lot
