### ISSUE TITLE
has any plan for support multi tenant  ?

### ISSUE THREAD

**Issue by mvbn6789** [casbin/casdoor#289]
I have view casdoor document and Is there any plan for support multi tenant  like keycloak realm model

**Comment by hsluoyz** [comment]
@mvbn6789 we have the organization concept: https://casdoor.org/docs/organization/overview which is similar to realm. It's a container for users.

**Comment by mvbn6789** [comment]
thank you for  your  quickly reply (*￣︶￣) I will try it

**Comment by ccdd4ever** [comment]
> @mvbn6789 we have the organization concept: https://casdoor.org/docs/organization/overview which is similar to realm. It's a container for users.

It looks like idp is global instead of belong to a specified tenant?

**Comment by hsluoyz** [comment]
@ccdd4ever yes, is there a problem?

**Comment by hsluoyz** [comment]
@ccdd4ever good point, in Casdoor, `Relm（Tenant)` is actually called `Organization`, we will support to add providers inside the Organization scope, it this OK?

If this is OK, you can create a new issue to track this

**Comment by ccdd4ever** [comment]
> @ccdd4ever good point, in Casdoor, `Relm（Tenant)` is actually called `Organization`, we will support to add providers inside the Organization scope, it this OK?
> 
> If this is OK, you can create a new issue to track this
Thanks for relpy. 
Issue:
https://github.com/casdoor/casdoor/issues/1217
