### ISSUE TITLE
Any plan for support  Ldap authentication when check user password login ?

### ISSUE THREAD

**Issue by mvbn6789** [casbin/casdoor#290]
I start casdoor project and  config ldap . Now ldap fetch user is ok but it seems Not support ldap auth user 
Alse I have  view the source code . password check by database password data and New ldap user default password is "123"

https://github.com/casbin/casdoor/blob/e4846807cd436b5a3911a602ffa8dcabdee3f1e4/controllers/auth.go#L189

Any plan for support  Ldap authentication when check user password login ?

**Comment by hsluoyz** [comment]
@sh1luo @WindSpiritSR

**Comment by hsluoyz** [comment]
@ComradeProgrammer plz take a look at this issue as next step

**Comment by hsluoyz** [comment]
@mvbn6789 done at: https://github.com/casbin/casdoor/pull/354
