### ISSUE TITLE
The account widget position is not correct sometimes

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#294]
See: http://1.13.13.178:8000/ deployed by @sh1luo 

![image](https://user-images.githubusercontent.com/3787410/132982890-eb4ec340-d7d6-4f1c-949d-bbd221aebc10.png)

But for some other cases, like the official demo: https://door.casbin.com/ , the position is correct:

![image](https://user-images.githubusercontent.com/3787410/132982906-de536441-8786-4a01-b2ba-7889e2748ba8.png)

We need to fix this bug.

**Comment by turbodog03** [comment]
working on this
