### ISSUE TITLE
Frontend : Modularizing Components and Make them responsive

### ISSUE THREAD

**Issue by sourabhmandal** [casbin/casdoor#30]
The current folder structure is highly disorganized and hard to navigate. Many components can be modularized which will in turn reduce the amount of code drastically.
I am proposing following folder structure 
--| src
--|--| **assets**
--|--|--| logo.png
--|--| **components**
--|--|--| CustomGithubCorner.js
--|--|--| Footer.js
--|--|--| Navbar.js
--|--|--| SelectLanguageBox.js
--|--|--| AuthProvider.js
--|--|--| Face.js
--|--|--| Utils.js
--|--| **pages**
--|--|--| AccountPage.js
--|--|--| ApplicationEditPage.js
--|--|--| ApplicationListPage.js
--|--|--| HomePage.js
--|--|--| LoginPage.js
--|--|--| OrganizationEditPage.js
--|--|--| OrganizationListPage.js
--|--|--| ProviderEditPage.js
--|--|--| ProviderListPage.js
--|--|--| TokenEditPage.js
--|--|--| TokenListPage.js
--|--|--| UserEditPage.js
--|--|--| UserListPage.js
--|--| **config**
--|--|--| Conf
--|--| **locale**
--|--|--| en.json
--|--|--| zh.json
--|--| **backend**
--|--|--| Auth.js
--|--|--| AuthBackend.js
--|--|--| AuthCallback.js
--|--|--| ApplicationBackend.js
--|--|--| OrganizationBackend.js
--|--|--| ProviderBackend.js
--|--|--| TokenBackend.js
--|--|--| UserBackend.js

Allow me to work on it... will be done in 2 days.

**Comment by hsluoyz** [comment]
Thanks for the advice, and I will do the refactoring job when necessary. The specific functionality implementation is recommended for other contributors.
