### ISSUE TITLE
for the 3rd-party login of WeCom and other office software, it can be automatically bound with the organization

### ISSUE THREAD

**Issue by khlipeng** [casbin/casdoor#306]
for the 3rd-party login of WeCom and other office software, it can be automatically bound with the organization

**Comment by hsluoyz** [comment]
@khlipeng hi, I cannot understand your question. Can you be more specific?

**Comment by hsluoyz** [comment]
ping @khlipeng

**Comment by khlipeng** [comment]
>

**Comment by hsluoyz** [comment]
@khlipeng hi, why close?

**Comment by khlipeng** [comment]
我用中文回复吧，本来我想提的是，通过企业微信扫码登录时，自动绑定到指定组，另外人可以在多个组内，基础信息只有一份，但之前看了下设计，好像用户信息是根据组来注册决定的。

**Comment by khlipeng** [comment]
@hsluoyz 我用中文回复吧，本来我想提的是，通过企业微信扫码登录时，自动绑定到指定组，另外人可以在多个组内，基础信息只有一份，但之前看了下设计，好像用户信息是根据组来注册决定的。

**Comment by khlipeng** [comment]
@hsluoyz 针对办公通讯软件而言，一个集团企业可能会拥有多个企业微信/飞书组织（我司就是），我也开发了企业的 SSO 系统。而通过办公通讯软件绑定的用户而言，针对企业，还会有一些特殊权限，比如内网的VPN / Git 权限等等，如果用户从相关通讯软件下被离职，那么用户也会随着从组织解绑。纯属个人经验

**Comment by khlipeng** [comment]
另外，关于三方登录的方式，建议使用服务插拨、插件等方式处理。这样，在接入一些三方或私有的一些三方系统而言，会更方便，只需要定义好相关协议即可。

**Comment by hsluoyz** [comment]
> @hsluoyz 针对办公通讯软件而言，一个集团企业可能会拥有多个企业微信/飞书组织（我司就是），我也开发了企业的 SSO 系统。而通过办公通讯软件绑定的用户而言，针对企业，还会有一些特殊权限，比如内网的VPN / Git 权限等等，如果用户从相关通讯软件下被离职，那么用户也会随着从组织解绑。纯属个人经验

你的意思是Casdoor与企业微信/飞书里的用户、组、角色做双向同步，如果一个用户在企业微信被删除，则Casdoor这边也同时删除是么

**Comment by hsluoyz** [comment]
> 另外，关于三方登录的方式，建议使用服务插拨、插件等方式处理。这样，在接入一些三方或私有的一些三方系统而言，会更方便，只需要定义好相关协议即可。

我们本想实现这个效果，但是遇到一个问题，Go是静态编译型语言，没有办法把插件代码（也是Go）动态加载进来。Go的插件化这块有没有好的practice呢？

**Comment by khlipeng** [comment]
> 

是的，准确的来说，是解除关系。

**Comment by khlipeng** [comment]
> > @hsluoyz 针对办公通讯软件而言，一个集团企业可能会拥有多个企业微信/飞书组织（我司就是），我也开发了企业的 SSO 系统。而通过办公通讯软件绑定的用户而言，针对企业，还会有一些特殊权限，比如内网的VPN / Git 权限等等，如果用户从相关通讯软件下被离职，那么用户也会随着从组织解绑。纯属个人经验
> 
> 你的意思是Casdoor与企业微信/飞书里的用户、组、角色做双向同步，如果一个用户在企业微信被删除，则Casdoor这边也同时删除是么

是的，准确来说，是解除关系

**Comment by khlipeng** [comment]
> > 另外，关于三方登录的方式，建议使用服务插拨、插件等方式处理。这样，在接入一些三方或私有的一些三方系统而言，会更方便，只需要定义好相关协议即可。
> 
> 我们本想实现这个效果，但是遇到一个问题，Go是静态编译型语言，没有办法把插件代码（也是Go）动态加载进来。Go的插件化这块有没有好的practice呢？

1、可以通过服务插拨的方式，以 http 请求为例，将扩展的三方登录以服务的方式独立开，启动时主动向 casdoor 注册三方信息，并通过心跳保活，然后进行后续的逻辑处理。

2、go 需要动态加载来扩展功能，最好的方式通过 plugin 来处理，具体你可以写点 demo  实验下，还是比较简单的

**Comment by khlipeng** [comment]
> > > @hsluoyz 针对办公通讯软件而言，一个集团企业可能会拥有多个企业微信/飞书组织（我司就是），我也开发了企业的 SSO 系统。而通过办公通讯软件绑定的用户而言，针对企业，还会有一些特殊权限，比如内网的VPN / Git 权限等等，如果用户从相关通讯软件下被离职，那么用户也会随着从组织解绑。纯属个人经验
> > 
> > 
> > 你的意思是Casdoor与企业微信/飞书里的用户、组、角色做双向同步，如果一个用户在企业微信被删除，则Casdoor这边也同时删除是么
> 
> 是的，准确来说，是解除关系

另外，对于用户和组的关系，建议是用户和组是一对多的关系，一个用户可以在多个组里面

**Comment by hsluoyz** [comment]
@khlipeng 可以加入我们的QQ群吗？645200447  QQ群主要是以中文为主的，GitHub保持英文信息的流通
