### ISSUE TITLE
Provide our Go backend API docs (via Swagger) in the web portal

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#31]
We use Beego as the backend web framework. Beego has a good integration for automated API docs like Swagger: https://beego.me/docs/advantage/docs.md

We need to integrate it and show a "Swagger" button in the top NavBar, the user can click into the API docs page and know what API we have provided in: https://github.com/casbin/casdoor/blob/master/routers/router.go , so they can directly call Casdoor via API instead of the frontend.

The finished Swagger UI would be something like: https://petstore.swagger.io/ , but it will be hosted directly in our Go backend (like: https://door.casbin.com/swagger).

![image](https://user-images.githubusercontent.com/3787410/112757984-a06f4f00-901e-11eb-8608-cda084621d50.png)

Maybe we also need to add comments to our public API functions, so the API docs can be generated.

**Comment by Kininaru** [comment]
Working on this.
