### ISSUE TITLE
Upgrade to Swagger UI 4.x for Casdoor API docs, and fix the Swagger tags

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#313]
Casdoor uses Beego, which helps automatically generate API docs at `/swagger` path (https://beego.me/docs/advantage/docs.md) like: https://door.casbin.com/swagger/

![image](https://user-images.githubusercontent.com/3787410/140603570-7e3dc279-23bb-4f25-b80a-918401f66e03.png)

Based on a user request: https://v2ex.com/t/803669#r_11042731 , we are still using Swagger UI 3.x and we need to upgrade to Swagger UI 4.x, which is just released several days ago. We need to find a way to upgrade it. I have raised an issue here: https://github.com/beego/bee/issues/809

Meanwhile, we should also show correct tags in the Swagger UI page, like under "organization" tag will list all organization-related APIs. The following Beego code is used to control the swagger.json generating behavior. We should tune it to make it right. (see: https://github.com/beego/bee/issues/618)

https://github.com/casbin/casdoor/blob/9e920181d20ada684b0c01c3a306ab55d3b6bbe6/routers/router.go#L32-L41

Here's an example of Swagger UI 4.x: http://petstore.swagger.io/

![image](https://user-images.githubusercontent.com/3787410/140603592-55301fc3-7eae-4298-99a4-afee75d54ddd.png)

**Comment by seriouszyx** [comment]
What I learnt from [this issue](https://github.com/beego/bee/issues/463) is `Swagger.json` follows version2 and version3 is the `Swagger UI`. So our [UI version](https://github.com/casbin/casdoor/blob/master/swagger/swagger-ui.css.map) is already 3.

**Comment by hsluoyz** [comment]
@seriouszyx I misunderstood the Swagger version and Swagger UI version previously. Now the issue looks OK.

**Comment by hsluoyz** [comment]
@seriouszyx can you work on this issue?

**Comment by hsluoyz** [comment]
@seriouszyx great, the PR has been merged. Can we also group the APIs in Swagger UI like this?

![image](https://user-images.githubusercontent.com/3787410/140912585-f597f37c-0a42-41f8-9d86-7bd0c8129c1e.png)

**Comment by seriouszyx** [comment]
@hsluoyz I'm looking for some ways... But it seems Beego does not support using `@Tags` annotations. And our API does not use URLs for classification like in the Beego documentation.

```go
func init() {
    ns :=
        web.NewNamespace("/v1",
            web.NSNamespace("/customer",
                web.NSInclude(
                    &controllers.CustomerController{},
                    &controllers.CustomerCookieCheckerController{},
                ),
            ),
            web.NSNamespace("/catalog",
                web.NSInclude(
                    &controllers.CatalogController{},
                ),
            ),
            web.NSNamespace("/newsletter",
                web.NSInclude(
                    &controllers.NewsLetterController{},
                ),
            ),
            web.NSNamespace("/cms",
                web.NSInclude(
                    &controllers.CMSController{},
                ),
            ),
            web.NSNamespace("/suggest",
                web.NSInclude(
                    &controllers.SearchController{},
                ),
            ),
        )
    web.AddNamespace(ns)
}
```

**Comment by hsluoyz** [comment]
@seriouszyx we can change our `init()` code to use `NSNamespace` and `NSInclude`. But we will not change the API path. Is this possible?

**Comment by seriouszyx** [comment]
@hsluoyz I will have a try.

**Comment by hsluoyz** [comment]
@seriouszyx is busy with other issue. @ComradeProgrammer can you have a try for this? It should not be very difficult I think.
