### ISSUE TITLE
Bug: wrong password format status when signing up

### ISSUE THREAD

**Issue by Abingcbc** [casbin/casdoor#342]
![image](https://user-images.githubusercontent.com/34068205/144102140-377654b5-807a-4a97-bc19-d50ec1d6e2be.png)

The status shows that the password format is valid, but when clicking `sign up`, the message shows the password format is invalid.

**Comment by hsluoyz** [comment]
@Abingcbc good finding! Given this is a very easy issue, can you fix it by yourself?

**Comment by hsluoyz** [comment]
Done by: https://github.com/casbin/casdoor/commit/667158f585d9aa209e72d04b3cbde25cc4354ed2
