### ISSUE TITLE
Implement Email verification

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#35]
You can refer to the code in Casbin-forum: https://github.com/casbin/casbin-forum

**Comment by Shogue21** [comment]
Hey there! I'm interested in working on this. Are you looking for an email verification like sending an email to verify after they sign up or verify the email during sign up (i.e. not allowing them to sign up if it is not an existing email)?

**Comment by hsluoyz** [comment]
@Shogue21 yes, and we may also send Emails to users when new reply comes to the topic (just like what happens now in GitHub).

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casdoor/pull/55
