### ISSUE TITLE
Failed to authenticate APISIX with Casdoor

### ISSUE THREAD

**Issue by hamlinzheng** [casbin/casdoor#358]
### Description

I try to test APISIX SSO authentication based on Casdoor, when I access a protected resource, the page can be redirected to the login page of casdoor, but when I enter the account password, an error appears on the page. 

Please allow me to describe the process.

### Casdoor Deploy

I use `docker-compose` to test Casdoor with `master` branch, my `conf/app.conf` is:

```yaml
appname = casdoor
httpport = 8000
runmode = dev
SessionOn = true
copyrequestbody = true
driverName = mysql
dataSourceName = root:123456@tcp(db:3306)/
dbName = casdoor
redisEndpoint =
defaultStorageProvider = 
isCloudIntranet = false
authState = "casdoor"
httpProxy = "127.0.0.1:10808"
verificationCodeTimeout = 10
initScore = 2000
logPostOnly = true
oidcOrigin = "http://localhost:8000"
samlOrigin = "http://localhost:8000"
```

And run with `docker-compose -p docker-casdoor up`

Then I add an application in casbin website at http://localhost:8000/applications. Also, I add `http://127.0.0.1:9080/` to `Redirect URLs` list. Then when i visit http://localhost:8000/.well-known/openid-configuration, it will return json data.

### APISix Deploy

I use `docker-compose` to test APISix with [apisix-docker](https://github.com/apache/apisix-docker) `master` branch, refer to https://apisix.apache.org/docs/apisix/getting-started/#step-1-install-apache-apisix

And I add a route with:

```shell
$ curl  -XPOST 127.0.0.1:9080/apisix/admin/routes -H "X-Api-Key: edd1c9f034335f136f87ad84b625c8f1" -d '{
  "uri": "/*",
  "name": "apisix_casdoor_test",
  "plugins": {
    "openid-connect": {
      "client_id": "07860a229bd0b162cdfa",
      "client_secret": "ea02b27ecde894a8915464a270a8b38c9373fe3e",
      "discovery": "http://172.17.0.1:8000/.well-known/openid-configuration",
      "introspection_endpoint_auth_method": "client_secret_post",
      "logout_path": "/logout",
      "realm": "master",
      "redirect_uri": "http://127.0.0.1:9080/",
      "bearer_only": false,
      "realm": "master"
    }
  },
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org:80": 1
    }
  }
}'
```

### Login test

When I visit http://localhost:9080/get, it will be redirected to casbin login page, as shown below:
![image-20211212020717046](https://user-images.githubusercontent.com/42463835/145687703-b763a5cc-94da-4100-840b-654cdd284fde.png)
However, When I enter the username  password and click `login`, an error occurred with `500 Status Code`, as shown below:
![image-20211212021422039](https://user-images.githubusercontent.com/42463835/145687707-0b77f481-c43b-41ea-bf5a-6ec1e6f3f484.png)

And APISix error_log is:

```yaml
2021/12/11 18:12:40 [error] 52#52: *41910925 [lua] openidc.lua:1378: authenticate(): request to the redirect_uri path but there's no session state found, client: 172.27.0.1, server: _, request: "GET /?code=1df1aab05a9e0106dbdf&state=5e47ec804e01959e2216c035f43b6194 HTTP/1.1", host: "127.0.0.1:9080", referrer: "http://172.17.0.1:8000/"
2021/12/11 18:12:40 [error] 52#52: *41910925 [lua] openid-connect.lua:297: phase_func(): OIDC authentication failed: request to the redirect_uri path but there's no session state found, client: 172.27.0.1, server: _, request: "GET /?code=1df1aab05a9e0106dbdf&state=5e47ec804e01959e2216c035f43b6194 HTTP/1.1", host: "127.0.0.1:9080", referrer: "http://172.17.0.1:8000/"
2021/12/11 18:12:40 [warn] 52#52: *41910925 [lua] plugin.lua:680: run_plugin(): openid-connect exits with http status code 500, client: 172.27.0.1, server: _, request: "GET /?code=1df1aab05a9e0106dbdf&state=5e47ec804e01959e2216c035f43b6194 HTTP/1.1", host: "127.0.0.1:9080", referrer: "http://172.17.0.1:8000/"

```

### Replenish

- APISix use `openid-connect` plugin provide authentication and introspection capability, the doc is [here](https://apisix.apache.org/docs/apisix/plugins/openid-connect/)
- The `openid-connect` plugin use **[lua-resty-openidc](https://github.com/zmartzone/lua-resty-openidc)** library

**Comment by Steve0x2a** [comment]
Hi, the problem has been located, and it is related to the fact that the returned information from casdoor does not match apisix.

We will fix it as soon as possible, if you want to use it as soon as possible, you can try using Token Introspection, our supported bearer code method for accessing resources.

Also, during my debugging (using the same docker deployment as you), I get an openresty error at the last step: Request Header or Cookie Too Large, if you have a solution for this, I'd appreciate your help!
