### ISSUE TITLE
Bug: crash when init built-in user

### ISSUE THREAD

**Issue by ComradeProgrammer** [casbin/casdoor#362]
When a brand new user start to user casdoor, casdoor will insert the build-in user into database, which can lead to a panic in current version .
```
xxx@xxx:~/xxxxxxx/casdoor$ go run main.go
[xorm] [info]  2021/12/12 20:39:09.671852 PING DATABASE mysql
panic: Error 1364: Field 'ranking' doesn't have a default value

goroutine 1 [running]:
github.com/casbin/casdoor/object.AddUser(0xc00044a700, 0xc00044a700)
        /home/xxx/workspace/casdoor/object/user.go:326 +0x230
github.com/casbin/casdoor/object.initBuiltInUser()
        /home/xxx/workspace/casdoor/object/init.go:73 +0x21d
github.com/casbin/casdoor/object.InitDb()
        /home/xxx/workspace/casdoor/object/init.go:21 +0x2a
main.main()
        /home/xxx/workspace/casdoor/main.go:33 +0x2b
exit status 2

```
(sorry I need to hide some personal information with xxx)
The apperance rate of this bug is 100% for brand new users whose database hasn't got a table called 'casdoor'

I have fully examined this bug and I will explain the reason of this bug later ,and ask for further opinion from @hsluoyz  @nomeguy about how to fix it

**Comment by ComradeProgrammer** [comment]
The reason is as follow:

In a recent change introduced by @nomeguy in commit eca1d23e35174a26cdbd00bc8ee064b286b74e9c
https://github.com/casbin/casdoor/blob/94c78593fc693569c773df3f0bebe339ff82f8a6/object/user.go#L54
 This attribute 'Ranking' was set to auto increment, while the primary key of this table is still another two attrubutes "Owner" and "Name"
https://github.com/casbin/casdoor/blob/94c78593fc693569c773df3f0bebe339ff82f8a6/object/user.go#L25
https://github.com/casbin/casdoor/blob/94c78593fc693569c773df3f0bebe339ff82f8a6/object/user.go#L26


However
1. Mysql doesn't support non-primary key to be set as "auto increment"
2. But setting ranking to primary key won't help, because 

2.1 xorm doesn't support non-primary key to be set as  "auto increment". You can find out this in the xorm source code
https://gitea.com/xorm/xorm/src/commit/303b1aeb7772ebd6253c72ba4853ce8cd3dadb44/dialects/dialect.go#L324
2.2 xorm doesn't support auto increment on primary key when there are  more than 1 primary key, 
see
https://gitea.com/xorm/xorm/src/commit/303b1aeb7772ebd6253c72ba4853ce8cd3dadb44/dialects/dialect.go#L320
and 
https://gitea.com/xorm/xorm/src/commit/303b1aeb7772ebd6253c72ba4853ce8cd3dadb44/dialects/mysql.go#L647

so when the table is created, the "ranking " attribute in mysql  is actually int, **without auto increament, without default value**, which lead to the error "Field 'ranking' doesn't have a default value"

**Comment by hsluoyz** [comment]
Done at: https://github.com/casbin/casdoor/commit/8d8c662e58a44e455936cd92853ed781db3f2614
