### ISSUE TITLE
Fix the WeCom provider

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#363]
See details at: https://v2ex.com/t/803669#r_11152422

Also the demo: https://door.casbin.com/

![image](https://user-images.githubusercontent.com/3787410/145713630-c0f393ff-2e48-498e-be95-f43ab8c50783.png)

![image](https://user-images.githubusercontent.com/3787410/145713634-ee808462-d30d-442e-98cf-98b8c8425f1d.png)

**Comment by Steve0x2a** [comment]
It looks like the demo site uses the Slient method for WeCom, and if  use Normal, may be able to login by qrcode?
![image](https://user-images.githubusercontent.com/17063270/145821400-cfe17b3e-d047-4442-8bf7-295fab0fdb65.png)
