### ISSUE TITLE
LDAP can't support Auto Sync

### ISSUE THREAD

**Issue by wxc978952419** [casbin/casdoor#369]
LDAP can't support Auto Sync
![image](https://user-images.githubusercontent.com/49092817/145925675-c3404272-182e-4a8b-a962-c1c66c3cf932.png)
![image](https://user-images.githubusercontent.com/49092817/145925737-f75af7a1-61b8-4aab-99a1-64c77977b9d7.png)

**Comment by hsluoyz** [comment]
@ComradeProgrammer
