### ISSUE TITLE
calling "api/register" even with correct data feilds gives error

### ISSUE THREAD

**Issue by sourabhmandal** [casbin/casdoor#38]
I called "api/register" with following json object
`
{
    "owner" : "builtin",
    "username" : "sourabh",
    "password" : "123",
    "name" : "sourabh mandal",
    "email" : "19mandal97@gmail.com",
    "phone" : "999"
}
`
But I got the following error

![a](https://user-images.githubusercontent.com/39632788/114298694-4b7b1080-9ad5-11eb-9828-62e2340a645c.png)

The `GetOwnerAndNameFromId()` expect a `username : "sourabh/organization`

The route works fine when I pass following payload
`
{
    "owner" : "builtin",
    "username" : "sourabh/organisation",
    "password" : "123",
    "name" : "sourabh mandal",
    "email" : "19mandal97@gmail.com",
    "phone" : "999"
}
`

Please tell me if its an error in CODE or the JSON PAYLOAD

**Comment by sourabhmandal** [comment]
I would suggest refactoring `GetOwnerAndNameFromId()` to eleminate this error

**Comment by hsluoyz** [comment]
@sourabhmandal this is not a bug. And we don't have enough time to do the input checking for now because this is endless.

Plz do some issues listed here: https://github.com/casbin/casdoor/issues
