### ISSUE TITLE
Is this project mysql only?

### ISSUE THREAD

**Issue by kuchaguangjie** [casbin/casdoor#45]
Seems don't support postgresql ? Just want to confirm that.

**Comment by hsluoyz** [comment]
@kuchaguangjie see: https://github.com/casbin/casdoor#config

```
Casdoor uses XORM to connect to DB, so all DBs supported by XORM can also be used.
```

XORM supports a lot of DBs including PostgreSQL: https://gitea.com/xorm/xorm#drivers-support

![image](https://user-images.githubusercontent.com/3787410/116387884-d9812600-a84d-11eb-83d5-258709ba0f13.png)

**Comment by kuchaguangjie** [comment]
It does support pg, but require some modification to work, since the code include some mysql specific config.

Refer to my fork & branch for postgres: https://github.com/kuchaguangjie/casdoor/tree/postgres

**The changes I made to make it work with postgresql:**

**1**. Create db by hand.
**2**. Edit `conf/app.conf`
> dataSourceName = "user=postgres password=xxxxxx host=127.0.0.1 port=5432 dbname=casdoor sslmode=disable"

**3**. Edit `object/adapter.go`
- In `InitAdapter()`  
    **Change**:
    > adapter = NewAdapter("postgres", beego.AppConfig.String("dataSourceName"))

- In `open()`  
    **Remove**:
    > if err := a.createDatabase(); err != nil {
    >     panic(err)
    > }

    **Change**:
    > engine, err := xorm.NewEngine(a.driverName, a.dataSourceName)`

**4**. Edit `authz/authz.go`
- In `InitAuthz()`
    **Change**:
    > a, err := xormadapter.NewAdapter("postgres", beego.AppConfig.String("dataSourceName"), true)

Then it will able to start.

------
BTW, I think the code could be refactored to support various db without changes. As you mentioned, it use XORM, and the `dataSourceName` config is for `github.com/casbin/xorm-adapter/v2`.

**Comment by hsluoyz** [comment]
@Kininaru
