### ISSUE TITLE
Starting port is 3000, not 7001

### ISSUE THREAD

**Issue by kuchaguangjie** [casbin/casdoor#46]
The README says it would start at `7001`, and `package.json` does use `"start": "set PORT=7001 && craco start",` but after start via `npm` or `yarn`, it starts at `3000`.

**Comment by hsluoyz** [comment]
@kuchaguangjie are you using Linux? This is because `set PORT=7001` is the Windows CMD grammar to set env var. But Linux uses another grammar in bash. I still don't know how to set env var for all OSs including Windows and Linux. Do you have any idea?

**Comment by kuchaguangjie** [comment]
@hsluoyz Yes, I am on Linux.
I usually set env via: `export`, just did a test, it works.

e.g
 `"start": "export PORT=7001 && craco start",`

**Comment by hsluoyz** [comment]
@kuchaguangjie yes. Linux uses export. Is there a way to be compatible for both?

**Comment by kuchaguangjie** [comment]
For `yarn`, you may create a `.env` file with line `PORT=7001`.
Refer: https://www.codegrepper.com/code-examples/javascript/craco+configure+port

---
To make it work for both `npm` and `yarn`, might need add `cross-env`, then use `cross-env PORT=1234`.

Refer:
https://stackoverflow.com/a/38785916/
https://www.npmjs.com/package/cross-env

**Comment by hsluoyz** [comment]
@kuchaguangjie this is a very good solution. Can you make a PR to fix it?

**Comment by kuchaguangjie** [comment]
PR: https://github.com/casbin/casdoor/pull/49

**Comment by hsluoyz** [comment]
@kuchaguangjie I confirmed the PR works on Windows 10. Thanks!
