### ISSUE TITLE
Yarn start get empty content.

### ISSUE THREAD

**Issue by kuchaguangjie** [casbin/casdoor#47]
When start via `yarn run start`, the page is empty.

But start with `npm run start`, it's ok.

And, after start via `npm` once, then start via `yarn`, the issue is gone.

Not sure what happened.

`yarn` version -> `1.22.10`,
`npm` version -> `6.14.11`,
`node version` -> `v12.22.0`,

`Chrome` version -> `Version 88.0.4324.182 (Official Build) (64-bit)` on `Linux` (mint mate 20, based on ubuntu).

**Comment by hsluoyz** [comment]
@kuchaguangjie 

> When start via yarn run start, the page is empty.

Can you open the devtools console and see if there are any JS errors?

**Comment by kuchaguangjie** [comment]
I removed `node_modules/`, then try again with `yarn` only, the issue didn't occur this time.

I did happen twice in different days before, when no `npm` is used.

I will update this post, if I see the issue again..

**Comment by hsluoyz** [comment]
@kuchaguangjie OK. Closed for now. Feel free to open it if it happens again.
