### ISSUE TITLE
Make a Casdoor middleware named "sso" for fiber

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#853]
It can be listed in: https://github.com/gofiber/fiber#-external-middleware

**Comment by hsluoyz** [comment]
@RyaoChengfeng

**Comment by xgenvn** [comment]
Fiber looks interesting, is there any starting idea on how to start with this, especially structurally? Will it be in examples or different repos?

**Comment by hsluoyz** [comment]
Not planned any more
